### ISSUE TITLE
Does this policy really apply to ALL custom code developed by agency employees?

### ISSUE THREAD

**Issue by murpup** [WhiteHouse/source-code-policy#132]
The policy states on line 89:

"Furthermore, this policy applies to all custom code created by covered agency employees in the course of their official duties, subject to certain exceptions noted below. "

There may be instances where agency employees who are power users, but not necessarily professional programmers, like scientists or engineers, will write small scripts or software tools that help them accomplish their day-to-day functions, but wouldn't really have much applicability to others beyond that - for example, maybe a fairly sophisticated Perl or Python script to manipulate Excel files, process some experimental data, or some such task.  These types of non-professional programmers may not have the inclination, or even have the knowledge, to operate the way this policy seems to mandate.  The will view the extra overhead involved as a waste of their time.

Is this policy really meant to capture every little script that a government employee creates such that it must be catalogued for sharing across the government and potentially released as an open source tool?  If so, then it seems highly burdensome.  The policy should be modified to apply only to custom source code that has significant development resources behind it (say $10k or 0.1 FTE), or has substantitive impact on the ability of an agency to conduct its mission.  If my wording is problematic, then OK fine, but then there should be some caveat that exempts the types of situations I have outlined above without the staff member needing to apply to the CIO for an exemption (which, in and of itself, is a burdensome process to the federal scientist or engineer).

**Comment by treysp** [comment]
I agree that it would be a ~~large~~ burden ~~(and waste of time)~~ to document every small script as you describe. However, it's critical that the policy cover scientific code associated with any publicly released scientific analysis - too often published results are opaque because the readers can't inspect the little analytic details that add up to something big. 

Related to #55, #128, and #101.

**Comment by sheepeeh** [comment]
> There may be instances where agency employees who are power users, but not necessarily professional programmers, like scientists or engineers, will write small scripts or software tools that help them accomplish their day-to-day functions, but wouldn't really have much applicability to others beyond that.
> [...]
> These types of non-professional programmers may not have the inclination, or even have the knowledge, to operate the way this policy seems to mandate. The will view the extra overhead involved as a waste of their time.

As someone who writes and references such code fairly regularly, I'm going to have to disagree on two fronts. Often, these types of functional hacks may be the most likely to be used by the "power user" 's professional community of practice because they actually solve problems particular to the community. In my field (libraries/archives/museums), these are often related to working with metadata. Some people might think a simple XSLT is too trivial to share, but trust me--we appreciate them!

Secondly, such scripts are usually (as you say) very small, meaning the documentation needed is similarly small. It's really not a huge burden to modify a canned README with the relevant commands or to use code comments/good naming practices to do the documentation for you. In fact, if I didn't do the latter, I would forget why I wrote a particular piece of code half the time. Never mind duplication across government--I'd have duplication across myself!

**Comment by treysp** [comment]
@sheepeeh Good points that hadn't occurred to me - interesting how one can't know what code would be useful to others until it's out in the wild to be found!

**Comment by murpup** [comment]
Do not mistake my intent.  I am not saying that we shouldn't require the release of these finished scripts/tools as part of the public record.  But I do have a problem with making it the engineer's responsibility to take on the additional overhead of doing their development out in the open on something like GitHub for such trivial tools (unless they want to).  This policy seems to be mandating just that. 

It isn't just the overhead of creating GitHub accounts, learning about version control, creating simple README files, etc.  As the policy gets implemented, there will also be agency bureaucratic overhead with getting the approval to even put custom code out there publicly.   I don't know of any engineer at my agency that is going to take that burden on just to write a toy Fortran program, small Python script, or Matlab script.

And even if we were to agree that tools like this could be worthy of an exemption due to the possible use of proprietary or pre-decisional data, this policy still puts the burden on the engineer to seek out this exemption from the agency CIO.  Again, this is simply not something that agency engineers will do.  They will ignore it and get their job done.

I would also like to point out that the more such trivial tools are published, the signal to noise ratio is going to drop (less signal, more noise) and you will have a harder and harder time finding tools useful to you.

**Comment by sheepeeh** [comment]
> I would also like to point out that the more such trivial tools are published, the signal to noise ratio is going to drop (less signal, more noise) and you will have a harder and harder time finding tools useful to you.

I think this is easy to address within the inventory schema. Just add a field called, say, **scope** with potential values of:
- utility script
- module
- full application
- ..etc

**Comment by jhourcle** [comment]
It might also be worth tracking the 'polish' of the software:
- ad-hoc / one off.
- it works, but it's a hack
- we're using it in production, but I don't know if I really trust it
- probably safe for other people to use

... and realistically, it's the little utility scripts that people write to get their job done that will likely be useful to other people ... sure, the big huge projects might be impressive, but only if you have a similar need.

And that makes me wonder -- so what do I do with all of the code that I wrote but scrapped, as it never worked as intended?

(insert disclaimer here about these being personal comments, and not that the of the agency I work for, blah blah blah).
