### ISSUE TITLE
Open source vs. copyright

### ISSUE THREAD

**Issue by murpup** [WhiteHouse/source-code-policy#135]
Open source is a license and not a statement of copyright.  Indeed, some open source organizations, like the Free Software Foundation (FSF), require that programmers assign over the copyright of any submitted patches to them before they will accept or use those contributions or patches in their open source programs.  This is so that there can be no question later as to who individually maintains the IP rights to individual lines of coding in the source base.  It would be a mess if FSF had to get the permission of every single individual copyright holder in its software before doing something like changing the license terms or something.

This brings up an interesting question when applied to the federal case.  

In the case of the federal government, it is clear that an agency cannot copyright information on its own, but copyright law allows the government to maintain copyright on coding assigned to it.  So how should agencies address the intellectual property rights of external contributors?  What if a member of the public submits some patches for a really good feature?  Who should own those lines of code?  Should the government require that the copyright on those lines be assigned to it (or declared to be public domain)?   

I suggest that either the policy be modified to address this situation, or, if that is not appropriate because it is getting into the weeds (which I grant may be the case here), OMB should ensure that this situation is addressed within the context of Project Open Source.  

My advice is that agencies should follow FSF's lead and develop policies (as well ready-made legally-binding forms) that will require contributors to either assign their copyrights to the Federal Government with no warranty, or declare the coding as public domain.  Can the government even do this?

Along the same lines, should agency procurement practices be changed to include clauses in contracts that require contractors to assign their software copyrights to the government?

**Comment by benbalter** [comment]
> In the case of the federal government, it is clear that an agency cannot copyright information on its own, 

Under 17 USC § 105 government work is not subject to _domestic_ copyright, but the internet, and thus open source software freely floats over political boundaries, and thus the international copyright implication of government-created code must be accounted for (for example, by releasing code under CC0 which disclaims copyright to the fullest extent the local jurisdiction allows). 

> but copyright law allows the government to maintain copyright on coding assigned to it. So how should agencies address the intellectual property rights of external contributors? What if a member of the public submits some patches for a really good feature? Who should own those lines of code? Should the government require that the copyright on those lines be assigned to it (or declared to be public domain)?

Code should be released under the least restrictive means, including public domain, again using something like CC0, or if not possible, under an open source license. Although a CLA may make the relationship explicit, [external contributors contribute to the project under the same turns as the project is distributed](http://ben.balter.com/2014/10/08/open-source-licensing-for-government-attorneys/#fn:1).

**Comment by jhourcle** [comment]
You need to not just deal with the assignment of ownership of the software itself, but there are also issues if there was anything novel in the software that might be eligible for other protections (eg, patents).

My understanding is that at my agency, if the contract is with a small business, then the default is that the property rights are bestowed upon the company.  If it's a larger company, the default is that the property rights are assigned to the government ... but there's a whole process for reporting 'new technology' that has to be done before you can attempt to go through the software release process ... and the 'new technology' process allows the contracting company to say that they'd like to claim ownership so that they can attempt to commercially exploit it.

What hasn't been clear to me is what the default is for subcontractors -- contracts will often be bid on by a small, minority owned business who then farms out work to larger companies.   I tried asking for what the status was for the software I was writing, but I ended up quitting the company when they were pressuring me to sign something that required me to give up rights to every idea I've ever had (which would've applied to stuff from before I started working for them).  And it was also binding on my heirs, so they'd have to give up all of their rights, too.

Oh, and this is related to my concerns from https://github.com/WhiteHouse/source-code-policy/issues/101 .

(insert disclaimer: my own thoughts, not my agency's or the company I'm contracting through, blah blah, etc.)
