### ISSUE TITLE
Problematic documentation requirements

### ISSUE THREAD

**Issue by ctubbsii** [WhiteHouse/source-code-policy#137]
There's a few problems with the documentation requirements on the "Federally Funded Custom Code as OSS" page, `5.2.f`:
1. Such requirements may conflict with part `a`, which encourages leveraging existing communities. Documentation standards cannot be mandated for existing communities, which may have their own standards. This section should be rewritten to clarify that it applies only when the project's community is controlled/managed by the government agency.
2. Paragraph `ii` declares that the "intended purpose" of the software be documented. The utility for OSS reuse can extend beyond any "intended purpose".
3. Paragraph `iv` declares that license details should be documented in this README, but it is common practice to place license details in a separate LICENSE, COPYING, or other similar file. The requirement to document the license details should not declare that they be necessarily exist in a README file, or it should be rephrased to clarify that the requirement can be satisfied by documenting the details in other locations.
4. Paragraph `v` requires build instructions "(if applicable)", but this seems unnecessary, since it will already be in the community's interest to provide such documentation if it is applicable and necessary. Many modern build systems are self-documenting, or follow generally accepted conventions and don't require additional documentation of this nature.

Rather than be so prescriptive, this section should only have a basic requirement to provide documentation of the project and the license under which it is provided.

**Comment by ultrasaurus** [comment]
In 5.2.f Providing "users and contributors with adequate documentation of source code" in no way conflicts with leveraging existing communities.  A project must have build instructions, description of purpose, license, etc. housed with its code in order for it to be useful to any community.  Typically, a project would be announced on a relevant mailing list or linked from a list of resources on a wiki, when relevant to a particular community.

Agreed that documentation, like license and build instructions, should be linked from, rather than required to be part of the README.  However, having a consistent place (with consistent naming) for open source software users and contributors to look for such references is of high value.

**Comment by ctubbsii** [comment]
@ultrasaurus I agree that the quoted portion does not conflict with leveraging existing communities. However, the prescriptive approach does (such as mandating those things appear in the README file specifically), if those existing communities have their own prescription for documentation (such as using a community Wiki or documentation system). Essentially, it's better to defer to the project's community of users and developers to determine what is "adequate [and appropriate] documentation", based on the target audience, standards of the community, etc.

Further, any "requirements" for government-produced software cannot be enforced if the project exists in a larger community beyond the government-producers of said software. So, it doesn't make sense to have these "requirements" unless the project is either `1)` controlled by government, or `2)` refers only to the initial public release prior to external community building.
