### ISSUE TITLE
"Federal agreement" undefined in Sec. 1?

### ISSUE THREAD

**Issue by tieguy** [WhiteHouse/source-code-policy#2]
"Federal agreement" \* may be a well-known term of art for procurement lawyers, in which case it may not be worth using as a defined term, but to a mere IP lawyer it appears to be both critical (easy way to avoid the bite of the regulation) and undefined. 

\* in Sec. 1, "This applies only to software developed in the performance of a Federal agreement"

**Comment by tieguy** [comment]
And having now read the definitions more thoroughly, I'd suggest what you want to do is define a Covered Agreement, parallel to Covered Agency, and use that instead of the more vague "Federal agreement".

**Comment by tieguy** [comment]
Closed by resolving in the next draft? Ignoring? ... ?

**Comment by chasingamy** [comment]
@tieguy Per [Issue #249 ](https://github.com/WhiteHouse/source-code-policy/issues/249), The public comment period has officially closed, and we closed all of the issues submitted before the deadline in order to officially count them as part of the public record. OMB will analyze **all** (emphasis mine) feedback submitted during the public comment period and revise the policy as necessary. No comments submitted during the public comment period will be ignored.

**Comment by tieguy** [comment]
Great, thanks for the clarification.
