### ISSUE TITLE
oss.md Clause 5.2 F Membership & Documentation

### ISSUE THREAD

**Issue by inetbiz** [WhiteHouse/source-code-policy#210]
On documentation, why not enlist the help of U.S. citizens? Form focus groups, beta testers and documentation writers. Create application process on open.gov and API into github to insert their github account into the appropriate team.

Modify document if this suggestion is considered.

**Comment by inetbiz** [comment]
Close before comments? This is NOT open source participation.

**Comment by konklone** [comment]
@inetbiz See #249. The public comment period was always set to close at midnight Eastern Time last night.

**Comment by chasingamy** [comment]
@inetbiz Per Issue #249 , The public comment period has officially closed, and we closed all of the issues submitted before the deadline in order to officially count them as part of the public record. OMB will analyze all feedback submitted during the public comment period and revise the policy as necessary. Further discussion can continue in new threads if you'd like, but they will not count as part of the official record.

**Comment by inetbiz** [comment]
This is not public comment. I'll stop participating in open source for this project if the White House is going to treat it like this.
