### ISSUE TITLE
Email Comment: Support for 100% Free Software

### ISSUE THREAD

**Issue by OMBPublicComments** [WhiteHouse/source-code-policy#225]
[Email Comment, received on 4/15/2016, at 11:45PM ET]

Hi,

I've been a computer programmer, systems administrator, web developer and free software activist for many years.

I think it is important that the government commit to producing and using only 100% Free Software
https://en.wikipedia.org/wiki/The_Free_Software_Definition

I believe the following points to each have mountains of supporting evidence, and are generally only disputed by entities trying to make money off of you:
1.  Proprietary software is less secure
2.  Proprietary software gives you less control/empowerment/freedom
3.  Proprietary software usually produces vendor lock-in. That is,
   it creates a dependency on a particular organization to
   continue to provide access/updates/fixes, etc.

There are many arguments in favor of proprietary software, but none of them are both ethical and true.

Please do the right thing.

Please do not cave to the powerful corporations. They just want you to accept their proprietary code because that way they have power over us and can abuse that power to restrict what we can do and make us give them money.

Free Software is essential to a free and empowered technologically advanced society.
## 

Jason Woofenden

**Comment by johnnewton** [comment]
I believe it is important to get maximum value for tax payers from their investment in Open Source Software. I understand the difference between Open Source and Free Source and I notice that the Free vs Open argument is only obliquely referenced in the conversation. What is known as Free Software can have the effect of not being usable in commercial software, even open source commercial software, and thus limit the potential contributions and reuse of software.

I would hope that the government thinks through the license very carefully. At Alfresco, we chose the LGPL license, a recognized Free Software license, as opposed to the GPL license, to support reuse of the Alfresco system. This was based upon the principles that Richard Stallman laid out in giving Free Software a level playing field in being embedded in commercial systems. Alfresco will continue to support the LGPL license.

However, we have found that there is generally greater reuse and collaboration with other, "more liberal" licenses such as Apache and MIT. This is because there is less restriction on how even open source companies can use the software. They are thus more likely to contribute back and participate in the development of the project. An example of this is our Activiti project, which is now embedded in other systems and with more companies participating in the development.

I assume that the objective of this project is not just to get the federal government to pay for everything, but to get a public/private collaboration on development of the software. This will be achieved by avoiding the GPL license and at least picking up the LGPL license. This may be necessary anyway if the target is only 20% open source.

**Comment by jplee** [comment]
The use of "more liberal" pushover licenses to try to attract more collaboration has backfired many times.  One of the most prominent examples is Mac OS X, a BSD-based system originally licensed under one of those "more liberal" licenses.  BSD's pushover license allowed Apple to take a copy of BSD and proprietarize it so that their version is no longer free (or "open source") software.

The BSD developers naively trusted that any person or company that takes and benefits from their code will naturally give back by contributing new features or code improvements.  Apple, however, has not.  The GNU General Public License (GPL) would have prevented this.

**Comment by OMBPublicComments** [comment]
[Email Comment, received on 4/17/2016, at 11:01PM ET]

[This comment has been added to this thread as the subjects are highly similar]

Please recognize and include free software in all government policies, not just open source software. All code should be released as free across all government bodies.  There should be a commitment to stop requiring or recommending the use of proprietary software, including proprietary JavaScript on any government-run or contracted server(s).  
Though Github has many benefits, software contributors should rely on government-run servers not government contracted corporate servers.  
This ensures the public through direct government intervention has access to content without binding contracts with corporations.

Thank you for your considerations.

Regards,
Peter Farver
Houston, TX

**Comment by johnnewton** [comment]
@jplee First of all I never mentioned BSD. Second I hardly think that anyone would consider Apache a pushover license. How would you substantiate a claim like that against Apache. I many ways it is one of the toughest licenses in terms of attribution and copyright. It is also what the web runs on. The free/livre/open source world could not run without either Apache or GPL.
