### ISSUE TITLE
Define "valid open source license" as meeting the Open Source Definition, rather than OSI approval

### ISSUE THREAD

**Issue by konklone** [WhiteHouse/source-code-policy#240]
_(I’m Eric, an engineer at [18F](https://18f.gsa.gov/), an office in the [U.S. General Services Administration](http://www.gsa.gov/) (GSA) that provides in-house digital services consulting for the federal government. I’m commenting on behalf of 18F; we’re an [open source team](https://18f.gsa.gov/2014/07/29/18f-an-open-source-team/) and happy to share our thoughts and experiences. This comment represents only the views of 18F, not necessarily those of the GSA or its Chief Information Officer.)_

[Appendix A’s footnote 49](https://sourcecode.cio.gov/Appendixa/#fn49) specifies a “valid open source license” as one that is approved by the Open Source Initiative (OSI):

> As of the publication date of this policy, a valid open source license is one that is approved by the Open Source Initiative (https://opensource.org/licenses). Further licensing considerations, including suggested licenses, will be provided via Project Open Source.

Defining a valid open source license is important, and the OSI list of approved licenses is a helpful guide. However, the above definition would be more practical for federal government use if it referenced OSI’s Open Source Definition, rather than their specific list of licenses.

Limiting licenses to those approved by the OSI will exclude a commonly used public domain dedication, Creative Commons Zero (CC0), which is not on the list of OSI-approved licenses. 

The Open Source Initiative has [not approved CC0](https://opensource.org/faq#cc-zero) because of concern over how CC0 explicitly disclaims the transfer of any patent rights. However, not all members of the open source community or federal community share this concern, and CC0 is still useful as an international public domain dedication for government work. 18F [applies CC0 internationally by default](https://github.com/18F/open-source-policy/blob/master/LICENSE.md) for all of its projects (whether in-house or procured). The CFPB [also applies CC0 internationally by default](https://github.com/cfpb/open-source-project-template/blob/master/TERMS.md), and one of its individual staff, @kimberlymunoz, submitted a comment to this policy (#209) about the benefits she’s observed in her work in doing so. Finally, the White House is using CC0 for many of its repositories, including the [repository for this draft source code policy itself](https://github.com/WhiteHouse/source-code-policy/blob/gh-pages/LICENSE.md).

For those government teams who do share OSI’s concern over patent language, Creative Commons included a helpful recommendation in their comment (#149) to include a non-assertion pledge:

> Thus, Creative Commons recommends that these government works should be released under the CC0 Public Domain Dedication, which waives any copyright that might apply, accompanied by a standard non-assertion pledge (nonassert) that indicates that the U.S. government will not to seek to enforce patent rights it may have against reusers of the software.

18F is considering implementing this recommendation.

More generally, we think the US government is in a better position recommending the use of a widely accepted definition like the OSI’s Open Source Definition, rather than an approved list maintained by any external organization (even one with a reputation and track record as excellent as that of the Open Source Initiative). The Open Source Definition is a powerfully helpful guiding light for open source, and the Open Source Initiative's approved list is a great reference point and recommendation, but there should be some room left for agency judgment.

To accomplish this, we recommend changing footnote 49 to read:

> As of the publication date of this policy, a valid open source license is one that meets  the Open Source Definition (https://opensource.org/osd). Further licensing considerations, including suggested licenses, will be provided via Project Open Source.

_(Edit: rewrote the last paragraph starting "More generally..." a little bit, to emphasize the usefulness of the OSI's approved list as a general reference point.)_

**Comment by konklone** [comment]
(I just renamed the title to more accurately reflect this comment's request.)

**Comment by david-a-wheeler** [comment]
I agree that the policy should reference the open source definition, not the OSI list, as the definition for what counts as open source software. The OSI list is fantastic, and I applaud the hard work that OSI does to maintain it. However, there are many open source software licenses that are not on the OSI list. CC0 is merely one of them. The fact that software is in the copyright public domain is also not in the OSI list and yet meets the open source definition.  So please do use the open source definition, not the list OSI maintains.

**Comment by massonpj** [comment]
While it is true that there are many licenses that would probably meet the criteria of the OSD that are not on the OSI's list, the list of approved licenses itself serves as a standard of trust, and the process for reviewing licenses ensures that the due diligence was done (through an open community) to assess and certify a license's compliance with the OSD.

Without citing the OSI's list of approved licenses, interpretation of a license could--I expect--be done by anyone, and confidence in "open source" will decrease. How will such claims be assessed, and who will do this work? The individual developers? Will this be a requirement of the adopters (in this case the government)? We at the OSI already see several examples of licenses and projects that claim to be open source (in alignment with the OSD), but are not. Sometimes these are honest mistakes--claims made by those simply unfamiliar with the details/requirements of open source licenses--and sometimes these are nefarious--made by those looking to dupe unsuspecting or naive users/communities/organizations. 

The result would be ambiguity and confusion (which licenses are open source like I think the OSD says it should be, who has to agree with any such claim?), and also greater costs for both those producing open source software, and adopting/integrating open source software, as all parties involved will need to invest resources to assess/certify if any new license claims do indeed meet the criteria of the OSD.

While the OSI list of approved licenses may not be complete, and arguments as to the status of various licenses (or other instruments like CC0 or public domain) exist, the list of OSI licenses is recognized as a standard by industry, governments and open source projects around the globe. If the lack of speed in license review is a hindrance, or the breadth of certified licenses is an issue, as an open and public process, the OSI License Review Process allows anyone to submit a license and/or participate in the process to assess that license. I am sure the OSI and open source community would appreciate any help to remedy and improve the process.

Patrick Masson
General Manager & Director
Open Source Initiative

**Comment by johnmod3** [comment]
+1 also : how licenses interact is extremely for determine what the resulting IP status of code is. OSI has done great work in this area. Older slide but see Wheeler: 
http://www.dwheeler.com/essays/floss-license-slide.html
"There are a large number of Free-Libre / Open Source Software (FLOSS) licenses, but only a few are widely used. The widely-used licenses tend to be compatible, i.e., the software can be combined to produce a larger work. The following “license slide” figure makes it easy to see when common licenses can be combined:
<pix>
![image](https://cloud.githubusercontent.com/assets/346086/15046642/e03490a2-12ae-11e6-9927-1a2aadda68f8.png)

In this figure, the shaded boxes are the names of different FLOSS licenses. An arrow from box A to box B means that you can combine software with these licenses; the combined result effectively has the license of B, possibly with additions from A. To see if software can be combined, just start at their respective licenses, and find a common box you can reach following the arrows (aka “following the slide”). For example, Apache 2.0-licensed software and GPLv2+-licensed software can both reach “GPLv3 or GPLv3+”, so they can be combined using GPLv3 or GPLv3+. This figure has been carefully crafted so following a path determines if two licenses are compatible. For more information you must examine the license text, but this gives the basic answer quickly.

At the left are the “permissive” licenses, which permit the software to become proprietary (i.e., not FLOSS). At the top left is “Public Domain”, which strictly speaking isn’t a license but in effect it works like one. You can do anything with public domain software, but it is rare; the software must be explicitly released to the public domain or be created by a U.S. Government employee in their official capacity. Next is the so-called “MIT” or “X11” license, which is very permissive (you can do just about anything except sue the author). Software under the MIT license is easily combined with the modern 3-clause Berkeley Software Distribution (BSD-new) license, which compared to the MIT license adds a clause forbidding the use of the author’s name to endorse or promote products without permission (it’s debatable if this clause actually does anything, since you typically have to have such permission anyway). Finally we have the Apache version 2.0 license.

At the right are the “strongly protective” (“strong copyleft”) licenses, which prevent the software from becoming proprietary. This includes the most popular FLOSS license, the GNU General Public License (GPL). The GPL has a version 2 (GPLv2) and 3 (GPLv3); a “+” afterwards means “version X or later”. GPLv2-only cannot be combined with the network-protective Affero GPLv3, but GPLv2+ (“version 2 or later”) can via GPLv3.

In the middle are the “weakly protective” (“weak copyleft”) licenses, a compromise between permissive and strongly protective licenses. These prevent the software component (often a software library) from becoming proprietary, yet permit it to be part of a larger proprietary program. This figure shows the rules when you are making other software part of the weakly protected component; there are other possibilities if you are only using the component as a library. The GNU Lesser General Public License (LGPL) is the most popular weakly protective license, and has a version 2.1 (LGPLv2.1) and 3 (LGPLv3). Note that LGPLv2.1 gives you permission to relicense the code under any version of the GPL since GPLv2. Another such license is the Mozilla Public License 1.1 (MPL 1.1), but the MPL has the serious drawback of being incompatible with the widely-popular GPL; you can’t even use an MPL module in a larger GPL’ed program.
