### ISSUE TITLE
Copyright, Copyleft, and Licensing?

### ISSUE THREAD

**Issue by michaeltryby** [WhiteHouse/source-code-policy#258]
This is great news! However, this source code policy does not adequately address copyright and licensing issues. I have come to see copyright and licensing as roadblocks to adoption, development, and maintenance of open source codes that requires resolution for this new policy to be successful. 

Why is it that the FTTA allows a Federal Agency to license a patent on research but can't license that research when it takes the form of software? In some circumstances the Federal Government is making substantial research and development investments and delivering intellectual property as software, yet our only choice is to place it in the Public Domain. We lack the tools to "protect" software like we have with other types of research products (protection can take many forms and the term is purposely being used loosely). 

Public Domain Dedication is just kicking the can down the road. A successful Federal Government Open Source Strategy is going to have to answer software copyright and licensing questions or it isn't going to achieve its full potential.

**Comment by johnmod3** [comment]
Congress should be pushed/asked to allow the US government to create and hold copyright - its time, way past time in fact for this to occur.

**Comment by ctubbsii** [comment]
@johnmod3 The relevant copyright law is [17 U.S. Code § 105](https://www.law.cornell.edu/uscode/text/17/105). It doesn't actually use the term "public domain". I'm not a lawyer, but what it seems to do is is prevent the U.S. Government from receiving copyright protections for its own works. Effectively, this prevents it from placing restrictions on the distribution of public government records and other publicly released government-produced works in the U.S. I think most people would argue that's a good thing, because the government is responsible to the public, and it shouldn't be restricting the free flow of information about government activities. Further, these works are, either directly or indirectly, created for the benefit of the public, and the public should be free to make use of them without copyright restrictions.

Lack of copyright protections for government-produced work does not prevent the government from producing open source software. Government can manage copyright from contracted work, it can assert international copyright, and it can document an open source copyright license to communicate the intersection of all rights available to the public from all contributors to an open source project, government employee or not.

Further reading which discusses this topic can be found [here](https://government.github.io/best-practices/copyright/).

**Comment by michaeltryby** [comment]
All Federal software is not the same. Public Domain is a one size fits all approach that we are stuck with because Federal Employees can not copyright their work. 

Sure Public Domain works for many projects; however, what if I am working on a project where a restrictive open source license like GPL makes more sense? We can't do it. What if the project has commercial significance and a licensing agreement makes sense? We can't do it. What if applying for a patent makes the most sense. Legal council says we can't patent software. 

I am finding the Public Domain doesn't work for some of my collaborators. Contributors from the EU can't dedicate their work to the Public Domain. What then? 

We need more tools in our toolbox.

**Comment by johnmod3** [comment]
Very very aware of all that and the work arounds, hacks,
 I;m just thinking maybe its time to ask / allow the US Government to
copyright its works to be concurrent with how the private sector does
things

---

John Scott
 240.401.6574
< jms3rd@gmail.com >
http://powdermonkey.blogs.com
@johnmscott

On August 17, 2016 at 1:39:45 PM, Christopher Tubbs (
notifications@github.com) wrote:

@johnmod3 https://github.com/johnmod3 The relevant copyright law is 17
U.S. Code § 105 https://www.law.cornell.edu/uscode/text/17/105. It
doesn't actually use the term "public domain". I'm not a lawyer, but what
it seems to do is is prevent the U.S. Government from receiving copyright
protections for its own works. Effectively, this prevents it from placing
restrictions on the distribution of public government records and other
publicly released government-produced works in the U.S. I think most people
would argue that's a good thing, because the government is responsible to
the public, and it shouldn't be restricting the free flow of information
about government activities. Further, these works are, either directly or
indirectly, created for the benefit of the public, and the public should be
free to make use of them without copyright restrictions.

Lack of copyright protections for government-produced work does not prevent
the government from producing open source software. Government can manage
copyright from contracted work, it can assert international copyright, and
it can document an open source copyright license to communicate the
intersection of all rights available to the public from all contributors to
an open source project, government employee or not.

Further reading which discusses this topic can be found here
https://government.github.io/best-practices/copyright/.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/WhiteHouse/source-code-policy/issues/258#issuecomment-240488383,
or mute the thread

**Comment by michaeltryby** [comment]
@johnmod3 Yeah, I agree. Maybe its time to take a more nuanced approach and stop lumping software with all the other "works" of the US Government.

**Comment by johnmod3** [comment]
my main point is that it really would simplify things, getting lawyers
involved is very slow - this question is being asked multiple times on many
email threads, but there is still the question of ‘is this real”
blogs post like this help:
https://government.github.io/best-practices/copyright/
- but its a .com opinion not a .gov approved and sanctioned one

On August 17, 2016 at 1:54:44 PM, Michael Tryby (notifications@github.com)
wrote:

@johnmod3 https://github.com/johnmod3 Yeah, I agree. Maybe its time to
take a more nuanced approach and stop lumping software with all the other
"works" of the US Government.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/WhiteHouse/source-code-policy/issues/258#issuecomment-240492787,
or mute the thread

**Comment by ctubbsii** [comment]
@johnmod3 I agree it would be helpful if some information/clarification about licensing and government copyright, like that on the government.github.io, site were formalized somewhere at cio.gov. I just don't think the right answer is to give government the ability to assert copyright, which would grant it the power to restrict information sharing, not improve it. "public domain" is the most "free" information can get. It does get confusing when thinking internationally, though. Again, it'd be helpful to have some of those best-practices published on cio.gov.

@michaeltryby There's not much stopping government from applying a GPL license to their open source projects. It just wouldn't be enforcable domestically for the specific contributions from civil servants acting in the course of their official duties. But, why does that matter? Do you really want the government pursuing copyright infringement lawsuits against folks who take out the civil servant contributions and use them elsewhere without explicit permission? Also, Government _can_ patent software. There are some concrete examples [published by NSA](https://www.nsa.gov/what-we-do/research/technology-transfer/assets/files/nsa-technology-transfer-program.pdf), NASA has a dedicated "IT and Software" section [in their patent portfolio](http://technology.nasa.gov/patents), and the Dept. of Energy also [lists many software patents](http://www.osti.gov/doepatents/search/term:software). I don't know where you're getting your information.

**Comment by johnmod3** [comment]
Can you explain this:
"I just don't think the right answer is to give government the ability to
assert copyright, which would grant it the power to restrict information
sharing, not improve it. "public domain" is the most "free" information can
get."

fact is NOT having a copyright on software has hampered the effective
release and rescue of it.

Incidentally NASA has the authority to copyright their software and its
worked out pretty well (openstack), one hack I always thought would be to
make NASA the pipeline for copyrighting government works
js

---

John Scott
 240.401.6574
< jms3rd@gmail.com >
http://powdermonkey.blogs.com
@johnmscott

On August 17, 2016 at 2:44:31 PM, Christopher Tubbs (
notifications@github.com) wrote:

@johnmod3 https://github.com/johnmod3 I agree it would be helpful if some
information/clarification about licensing and government copyright, like
that on the government.github.io, site were formalized somewhere at cio.gov.
I just don't think the right answer is to give government the ability to
assert copyright, which would grant it the power to restrict information
sharing, not improve it. "public domain" is the most "free" information can
get. It does get confusing when thinking internationally, though. Again,
it'd be helpful to have some of those best-practices published on cio.gov.

@michaeltryby https://github.com/michaeltryby There's not much stopping
government from applying a GPL license to their open source projects. It
just wouldn't be enforcable domestically for the specific contributions
from civil servants acting in the course of their official duties. But, why
does that matter? Do you really want the government pursuing copyright
infringement lawsuits against folks to take out the civil servant
contributions and use them elsewhere without explicit permission? Also,
Government _can_ patent software. There are some concrete examples are
published by NSA
https://www.nsa.gov/what-we-do/research/technology-transfer/assets/files/nsa-technology-transfer-program.pdf
and NASA has a dedicated "IT and Software" section in their patent portfolio
http://technology.nasa.gov/patents. The Dept. of Energy also lists many
software patents http://www.osti.gov/doepatents/search/term:software. I
don't know where you're getting your information.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/WhiteHouse/source-code-policy/issues/258#issuecomment-240508155,
or mute the thread

**Comment by ctubbsii** [comment]
@johnmod3 I don't know what you mean when you say "NOT having a copyright on software". That premise isn't even true. Even if the software is not subject to U.S. domestic copyright protections, it still has some international copyright protections.

I concede that not having the ability to apply domestic copyright protections may hinder releases... but I suspect the hindrance is mostly based on confusion over the status of the code, rather than a real technical or legal hindrance.

When I say "I just don't think the right answer is...", I'm referring to what it means for ["Copyright protection under this title" to be "available" under 17 U.S. Code § 105](https://www.law.cornell.edu/uscode/text/17/105). The "available" protections it is referring to is the legal recourse the copyright holder has against infringement. By saying you want these other categories of works to "have copyright", you're saying that you want the U.S. Government to have legal recourse to stop infringement, and to retain exclusive control over the ability to copy/modify/redistribute, unless it _explicitly_ grants you that permission with a license (potentially for a fee). Right now, as "public domain", those permissions are implicit... you don't need to explicitly ask the government for permission... you don't need to ask anybody, and you don't need to restrict yourself to abiding by any conditions of a license. That's what it means to be "in the public domain", and that is the most "free" use I can think of.

That's why I think adding copyright protections to these works would be a generally bad idea. I don't think the government should have the power to restrict sharing of government-produced information in that way.

What I do think would help, is some explicit clarification about the status of government works and what others are permitted to do with it under the the various potential statuses, such as: when it's produced in whole or in part by a contractor, when it's created exclusively by a civil servant, when it contains third-party contributions from the open source community, etc.

**Comment by konklone** [comment]
I co-authored this piece on public domain for government data (and software) with @JoshData, before I joined government, when I worked for the Sunlight Foundation:

https://theunitedstates.io/licensing/

It was endorsed by a broad swathe of civil society, and was a useful reference when 18F stood up its own [open source policy](https://github.com/18f/open-source-policy).

During the public comment period, [18F](https://github.com/WhiteHouse/source-code-policy/issues/76) and [CFPB](https://github.com/WhiteHouse/source-code-policy/issues/209) both discussed their positive experiences releasing software into the international public domain.

Personally, I would just note that, though removing the government's ability to hold copyright domestically is a matter of law and not the Constitution, copyright was [defined and justified in the Constitution](https://www.archives.gov/exhibits/charters/constitution_transcript.html) as supporting authors and inventors, not the government itself:

> To promote the Progress of Science and useful Arts, by securing for limited Times to Authors and Inventors the exclusive Right to their respective Writings and Discoveries.

**Comment by ctubbsii** [comment]
@konklone That's an interesting perspective. I like the general idea of being free, to the greatest extent possible, but there are lots of problems with CC0. First, it's not clear that you can actually waive copyright in jurisdictions which do not have the concept of "public domain" or copyright waivers. Further, it doesn't grant license to the use of patents (unlike ASL2, for example, which explicitly grants use). It also doesn't address contributions to pre-existing open source projects, or derivatives of them, or deal with the case of trying to support open source community development.

Really, the only case it seems appropriate for are: domestic consideration only, one-time ('drive-by') releases containing no patent concerns.

Further, it's generally best to use licenses which are accepted by the target community, and many folks stick to those approved by the Open Source Initiative, which [does not currently recommend](https://opensource.org/faq#cc-zero) using it for software.

Personally, I'm a big fan of the more permissive licenses over the copyleft and other restricted licenses, probably for similar reasons as you chose to use the phrase "greatest extent possible"  on that site to refer to software being free. I tend to recommend some of the more commonly accepted and well-known licenses, like ASL2, BSD, and MIT.

**Comment by konklone** [comment]
>  I like the general idea of being free, to the greatest extent possible, but there are lots of problems with CC0. First, it's not clear that you can actually waive copyright in jurisdictions which do not have the concept of "public domain" or copyright waivers. Further, it doesn't grant license to the use of patents (unlike ASL2, for example, which explicitly grants use). It also doesn't address contributions to pre-existing open source projects, or derivatives of them, or deal with the case of trying to support open source community development.

For those jurisdictions which have no concept of the public domain, CC0 contains a fallback license that attempts to simulate the general conception of the public domain. 

Patents are a thing, and [Creative Commons' comment on the White House source code policy](https://github.com/WhiteHouse/source-code-policy/issues/149) recommends an explicit patent disclaimer, something we're considering at 18F.

To support open source community development and handle the license status of contributions, 18F uses a [standard CONTRIBUTING.md file](https://github.com/18F/open-source-policy/blob/master/CONTRIBUTING.md) that establishes that contributions must be released under CC0 as well.

> Further, it's generally best to use licenses which are accepted by the target community, and many folks stick to those approved by the Open Source Initiative, which does not currently recommend using it for software.

We understand OSI's reservations (which relate to the lack of explicit patent language), but are comfortable with our assessment that CC0 meets the definition of open source. There are other standard open source licenses which also do not explicitly address patents.

**Comment by johnmod3** [comment]
@ctubbsii "I don't know what you mean when you say "NOT having a copyright on software". That premise isn't even true. Even if the software is not subject to U.S. domestic copyright protections, it still has some international copyright protections."
actually yes it is true, software not having some sort of copyright protection virtually ensures companies won't use for fear of not knowing what the legal status of that software is. 

If the US government were able to claim copyright and release it under a permissive license it would simplify how the government deals with IP civilians generate.

**Comment by michaeltryby** [comment]
Thanks for the stimulating discussion. I have learned a great deal. The variety of opinions expressed here ultimately serve my main point that we need clarification on copyright and licensing issues. I agree that Public Domain is a useful default. It is simple and philosophically appealing and we are currently making due with it; however, it quickly becomes impractical when trying to operate an open source style community project when the other parties involved have different motivations for participation. 

Case in point, the Federal Govt has been investing in the project I work on since 1970's. Decades of development and millions of dollars in investment. It has commercial significance and is widely used in industry. Trying to stand up an open source project around this code and getting all parties to play nice in the Public Domain is simply not feasible. Having some other options would reduce confusion and help promote development and maintenance of the source code outside the Govt which I assume is one of the goals of this policy.  

Community led open source development is not always a "release it and they will come" endeavor. Allowing copyright and alternative licensing options can be structured to help achieve the goals of this policy.

**Comment by mchogan** [comment]
My non-lawyer understanding... Copyright exists for a limited time, beginning when a work is created, and then expires releasing that work into the public domain. In contrast, federal government works are immediately released into the public domain, with no period of copyright protection. So the federally funded projects subject to the Code.gov policy are already in the public domain and all the CC0 license does is essentially attach a note to let people know.

I understand a license is needed to reuse code from a person because that person holds copyright, whether or not they want it, until copyright legally expires. Without a license, ability to reuse is unknown. From the discussion here, that situation doesn't seem to be an issue with federal code since a copyright period doesn't exist for that code.

**Comment by mattbailey0** [comment]
See also: https://github.com/presidential-innovation-fellows/code-gov-web/issues/28

**Comment by yoosefi** [comment]
Anything the government authors for public consumption is (or should be) automatically public domain.

**Comment by JoshData** [comment]
Folks, copyright law and federal IT are complicated and not something you can understand just by reading 17 USC 105. Unless you're an expert in this area, I would suggest that further comments be phrased in the form of questions rather than assertions.

**Comment by citizencontact** [comment]
I would generally agree with JoshData on being careful around legal matters about intellectual property and contract law (and both were being talked, like the GPL). There are issues related to trademark, patents and copyright which may have bearing and then complicated by contracts. And then there is the question of enforcement, for example, intellectual property often has common law implications like fair use, etc. Get the question well defined and ask some good lawyers is my suggestion.

**Comment by david-a-wheeler** [comment]
I've looked into this extensively.  Caveat: Not a lawyer, not a government lawyer, but have examined this for over 20 years.

If you want to see what the _current_ release rules are, see my paper "Publicly Releasing Open Source Software Developed for the U.S. Government": https://www.csiac.org/journal-article/publicly-releasing-open-source-software-developed-for-the-u-s-government/

The government _can_ hold copyrights if the work was developed by anyone other than a government employee performing his official duties (e.g., a contractor).  You can even put this in a contract, just include clause DFARS 252.227-7020.  (Less likely if you're not in the DoD, but it's certainly possible.)

The government _can_ hold copyright outside the US for something developed by a government employee, too.

The special case is a government employee who develops the software as part of his official duties.  In that case, the software does _not_ have a copyright in the US.

@johnmod3 - Great to hear from you!!!  I think the primary problem is lack of clarity.  The government can just stick a CC0 license on it, and that would apply everywhere.  The government can also slap on any OSS license, and just note that within the US there's no copyright so the conditions don't apply.  There are many reasons the government can't claim copyright - if it could, the abuses might be much worse.

**Comment by ckaran** [comment]
@david-a-wheeler assume that the Government is using standard OSI-approved licenses, and is putting together a note as you mention above; will that require the Government to specify that certain clauses in the license will always apply?  Are there any concerns about [severability](https://en.wikipedia.org/wiki/Severability) in that case?

**Comment by david-a-wheeler** [comment]
@ckaran - standard caveat, not a lawyer.

I don't see why severability would be an issue. In practice, copyright *always* has different timeframes in different countries (because the length of time is controlled by a particular country's laws). When it's under copyright, clauses related to copyright apply; when the copyright terms expire, within that country they no longer have any force.

**Comment by ckaran** [comment]
@david-a-wheeler I was less concerned with time frames and more concerned with someone trying to state that the entire license was invalid solely because a single clause was invalid.  That said, what you state about a particular country's laws makes for a *very* interesting legal headache as different countries may have different views on severability and validity of licenses...
