### ISSUE TITLE
Adopt and incorporate  VA - DoD Interagency  Data Rights language. 

### ISSUE THREAD

**Issue by rafael5** [WhiteHouse/source-code-policy#39]
The VA and DoD have invested considerable resources to establishing technical and legal frameworks for technical collaboration on software development because they are Congressionally mandated to interoperate. 

A most recent example is the VA-DoD Interagency Agreement established for co-development of software is linked here.  Of particular interest is the Data Rights section ((1.6.15 and its subsections):

https://github.com/vistadataproject/documents/blob/master/Submissions/src/VistAMetadata-2015-12-09-PWS.pdf

The Markdown version:

https://github.com/vistadataproject/documents/blob/master/Submissions/src/VistAMetadata-2015-12-09-PWS.md#data-rights

=> This might be a good template for inclusion in this Whitethous source code policy.

**Comment by mikeBeviBevi** [comment]
@rafael5 Please correct me if I'm wrong, but I'm not sure that the Data Rights Section holds up to U.S. government copyright laws.  Especially when the data that this source code policy refers to is supposed to be work done for the federal government either by its employees or contracted.
See:
 http://www.copyright.gov/title17/92chap1.html#105

**Comment by rafael5** [comment]
Stating the Data Rights section as an entire unit of text does not hold up to U.S. copyright laws is rather vague.   Can you be more specific? 
1. What specific section of the copyright law are you referring to? 
   And correspondingly:
2. What specific section  of the Data Rights language are you referring to?

**Comment by mikeBeviBevi** [comment]
@rafael5 I'm sorry, I was very vague and my last statement was not very helpful.  When I first read the document I did not see that there were subsections to 1.6.15.  That Data Rights Section is actually very great, thanks for sharing this.  My original concern was with lines 2-4 of 1.6.15,  since the government cannot hold a copyright for work that it produces.  However, I guess 1.6.15 is referring to work done under contract and transferred over to the government. 

So the Data Rights Section you mentioned suggests using the Apache 2.0 licence for any original works.  It has been suggested else where in these comments (by @johnmod3) that the Apache licence might be applicable to code released under this open source policy.  This seems reasonable, but Sections 2 and 3 of the Apache licence grant a copyright and grant a patent.  I wonder what this means for work done by a federal employee since the government cannot hold a copyright for that work.  Is that section just ignored? What are your thoughts?

**Comment by royfielding** [comment]
@mikeBeviBevi An open source software license like the Apache License (which I authored) is a set of permissions that are only needed _when_ the software is subject to exclusive rights. Hence, it is perfectly fine for a person who owns no rights in a given work to give you **their** permission to copy, use, etc., assuming they haven't claimed any specific copyright or patent.

For an open source project, the trick is to ensure that everyone who contributes to a given work, regardless of their employer, agree that their own contributions can be distributed under that license even if those contributions might be owned by some other entity. In other words, they state that the contribution can be licensed because those exclusive rights don't exist (the work is in the public domain), or owned by them, or owned by some other entity that has given them permission to license those rights. Consumers of an open source product are dependent on the project's ability to maintain those permissions over time, comprehensively, which is why many businesses prefer to adopt products from open source foundations, like the [Apache Software Foundation](https://www.apache.org/), which have adopted comprehensive policies regarding the licensing of contributions.

Hence, a government agency or employee can license their work under an open source license, like the Apache License, if they state that the license only applies where the public domain status is deemed insufficient permission. This is essentially the same as dual-licensing, though public domain isn't itself a license. IMO, this kind of license is necessary even when a work is 100% created by the US government, since the public domain requirements of USC do not extend outside the US.

Unfortunately, many people seem to think that CC0 is an open source license. It isn't. CC0 works fine as an open data license because the data is dead: there are no expected conflicts over contributions, trademarks, or patents. Open source licenses need more permissions because the expectation and desire is for a community to adopt, extend, and maintain the software over time. Dead code doesn't adapt.

**Comment by david-a-wheeler** [comment]
The CC0 license is an open source software license, because it meets all the requirements of the open source definition.  The OSI does not want to certify it as an open source software license, because they do not want to set certain precedents, but that is not the same thing as not being OSS. I will note that CC0 is already listed as an open source and/or Free software license under the Debian and Fedora lists.  

Now it is fair to point out that the CC0 license has effects that some people will not prefer. This is easily resolved by requiring the release of software as open source software by default, but allowing some flexibility in exactly which license may be used.  Problem solved.

**Comment by royfielding** [comment]
@david-a-wheeler CC0 does not meet the OSI definition part 7 because it explicitly disclaims rights necessary for use and import of the work that would otherwise (at the very least) be implied by an open source license. This is not a problem for documentation and data, so most open source projects will allow some contributions of CC0 work. However, it is a problem for software, and that is acknowledged by Creative Commons.

**Comment by mikeBeviBevi** [comment]
@royfielding Thank you Roy for your explanation.  I see where the Apache licence would make sense for work 100% done by government employees.  

I do wonder about these comments however: #151
