### ISSUE TITLE
Security of Code Needs to Be Established Before Sharing

### ISSUE THREAD

**Issue by johnpescatore** [WhiteHouse/source-code-policy#41]
Many tools and services exist to test source code or binaries for well known vulnerabilities. Government use of these tools, or government agencies requiring contractors or software suppliers,  has been minimal and inconsistent.

The world does not need more insecure code - this process needs to as a minimum require common process for code to be tested for "basic app development hygiene" before being submitted or at least before being accepted. 

NIST had fiddled around with such tools for over a decade now, this would be a good vehicle for them to move towards actual operational improvements in government software security.

John Pescatore

**Comment by johnmod3** [comment]
Agree that the gov should have some minimum standards for acceptance of code, but that should be set out in this policy

**Comment by abutterworth** [comment]
I think it may be more helpful, rather than waiting to share code before determining whether or not it's secure, to share first and then before implementation ensure that the software is secure. 

In this case since the software will be open source, more eyes earlier seems safer. 

I agree with your points on a minimum standard for code acceptance, but I think that's a separate issue.

**Comment by mikeBeviBevi** [comment]
I would disagree that more eyes = safer.  The purpose of labeling material as sensitive or classified is to limit the amount of eyes on that data.  

I think that this policy should not attempt to dictate coding standards too much, and I would ultimately leave that to the federal employee who is responsibly for integrating changes to baselines for a particular project.  There could a be a supplement that offers guidance on best practices and minimal standards to these employees.  It might make sense that each agency/project defines guidelines after meeting the minimums.

I think this policy should focus on the availability and governance of federal source code and not so much the coding standards.

**Comment by abutterworth** [comment]
@mikeBeviBevi, if the source code is going to end up public anyway it would be less safe to limit the view of that code to fewer people before its deployment. If there's sensitive material or data within the source code itself it should never become OSS and I think would be an exception for all of this. What downside are you foreseeing?

I fear that waiting to publish code until it's deemed secure would lead to a hesitancy to share at all or until some policy deadline comes up. 

I do like your point that coding standards should be left to the teams working on these projects.

**Comment by johnpescatore** [comment]
To require code be run through one of many available source code 
vulnerability analysis tools would require very little waiting. Releasing 
code with well known security vulnerabilities should be discouraged, much 
the way commercial cooks are discouraging from cooking without washing their 
hands first – doesn’t take long to wash.

**Comment by johnmod3** [comment]
@johnpescatore this is definitely best practice for accepting code (and should be encouraged in other policies). I'd rather see code released quickly and let the community review it

**Comment by mikeBeviBevi** [comment]
@abutterworth I was thinking just as @johnpescatore suggests.  Run a static analysis tool for known security flaws, set up some rules to look for patterns that might be might be suspected of being sensitive data.  

The policy currently states that the inventory would contain record of the federal open source projects and also other projects that have not been released to public.  I would want to run a diff on the code being submitted, to the code known to not be released to the public.  I'm trying to prevent a mistake where an employee loads up changes that have not been released to the public yet or the more nefarious situation where someone has gained access to data that is not not supposed to be made available to the public yet and is attempting to post it.  It would seem brazen to release such a thing on that forum but stranger things have happened. With the amount code that might be maintained on these servers, I don't know if this would be reasonable but, I would like to entertain the idea.  If the processing would take too long, then I guess I would be satisfied with this policy outlining ramifications and proper mitigation. 

I guess when I say secure I'm not saying that we need to ensure it is functional, that's for the community review.  

There are similar checks that are done on some secure messaging systems used in the federal government.  Most of the time its just a sanity check to make sure your uploading the data you think you are.

**Comment by johnmod3** [comment]
@mikeBeviBevi What you saying makes sense, but wouldn't scale across the entire government. There have been data leaks of code being released with ITAR material, usually get caught pretty quickly, cleaned/wiped, etc. and then everyone learns from the experience. NGA seems to be doing a fine job of releasing code to the public - code that should be released (as does NSA)

**Comment by rafael5** [comment]
I agree with mikeBeviBevi:  "the more eyes = the more secure"

=> The default should be that all  government code  - 100% -  is released to the public with only very special, well defined exceptions.

=> For example, the only code that should not be released to the public are actual security algorithms:   crypto algorithms, hashes, and the like.

And to enable redaction:

=> Software needs to be written such that it can be easily redacted with automated tools.  In other words,  it needs to be more configuration driven than procedural logic driven. This would allow easy redaction of sensitive information, such as replacement of a table of personally-identifiable information, rather than embedding personally identifiable or otherwise sensitive information in procedural code (making redaction of the sensitive information also destroy the code and business logic)

**Comment by seamustuohy** [comment]
There are a variety of other documents that regulate the security of code developed for the federal government. I believe that additional specific recommendations for how code should be audited within this policy muddies the water and will make it more difficult to adopt better methods in the future. I think that adding the option to delay "to establish the security of source code to be open sourced" in addition to the release exceptions laid out in section 6 would provide agencies the time to properly evaluate the  source code. Another option would be to directly reference another standard, document, policy, etc. which lays out guidelines so that it is easier to update the security practices as new methods become available.

**Comment by johnmod3** [comment]
in my experience when it comes to source code review: the gov customer is in no position to evaluate the 'goodness' of source code before release. Better to release first, then work thru the issues.

**Comment by abutterworth** [comment]
In arguing for releasing first and working through security issues later, I'm really thinking of developing in public. Developing in an open source way will allow the government to reap benefits from the community that are unforeseen. Developing in a silo to be released later removes this possibility.

For source code of software that is that is complete and already in use, I agree you'd want to make sure it's secure first. 

I think these are two situations that would require the different attitudes we are discussing.

**Comment by mbeckerle** [comment]
I very much disagree with the view that security can be insured or even improved through a pre-publish policy. 

New security vulnerabilities are discovered, so what is secure one day will be determined to be insecure the next when somebody figures out a new flaw/strategy to cause trouble. 

Understanding the security situation for the software you use is important, no doubt, but mandating that software must pass some bar in order to be shared.... not so much. The best model for open source is open-source from line-1. It's developed open-source, not is developed, and then source-code is published. Many benefits of open-source occur during the development cycle. It's not about whether the code is eventually "made open source" or not. It's much more about the change in the whole way the software is created from the start. 

Let me give you an example. On my project (which is open source, USG-funded), if I write code that I realize introduces a flaw or just risk of one that I might not fully understand. Or just reading the code I spot a flaw. That doesn't stop me from adding that code, or require me to fix that flaw. As a developer what I will do depends on the priorities at the time. Generally I will post an issue in the bug-tracker indicating the presence of the flaw. This stops nobody from pulling and using the software at any time, at any revision. They can fix the issue themselves, and contribute to the project, or just vote to raise the priority of that bug fix. Or maybe they're just evaluating the software with no intention of yet deploying it for any purpose where those flaws would matter. 

It's not possible to anticipate the various ways that a given piece of open source software may be useful to other projects.  

In general, I think the USG should simply have most projects use existing open-source infrastructures, existing open-source software components, and benefit from them and not really worry about adapting them, or creating USG-specific ideas to impose on them. 

It's not a community full of flaws that need improving. Open source development isn't something that has anything wrong with it that needs fixing before USG can use it more widely. It's a pretty successful tech paradigm now. Suitable for many things, not necessarily everything. 

I'm not saying it's perfect. One of the strengths of the open-source paradigm is that it is continuously evolving and improving. But lots of value is available just by using it.

**Comment by sephcoster** [comment]
Let's be careful not to conflate "open sourcing" code (posting your code to GitHub, BitBucket, wherever) and "accepting" code or "deploying" code. The ideal for me would be encouragement to work completely in the open so unfinished or unreviewed code might be the norm - and that should be totally fine. 

Because of this view, I'm opposed to policy-level requirements around scanning / acceptance before code is posted. 

I would advocate a total reduction in barriers to posting code in the open. Rather than implement any hurdles as policy because of concerns, let's instead look to provide recommendations and resources for a community of open source tools around scanning and security. That will be much more valuable and flexible in the long run.

Similar to @mbeckerle's argument, I read the policy as encouraging adoption of existing infrastructures / practices for making code available at which point maybe it gets re-used. I would expect that as multiple agencies / communities used applications and they got more popular you would start to see the same "more official" releases start to appear that you see in open source communities now.

Any agency / CIO level assessments, reviews, etc that are required to ensure code is secure or "acceptable" for their business would already be covered under existing policies and standards so I don't see that going away.

Any policy regarding review of code _before_ it is posted seems like it would also still be up to the agency. That said, there are already a number of scanning tools out there that can be easily tailored to catch sensitive content to help reduce the risk of spills. (You can re-use them easily because they're open source :smile: )

**Comment by johnpescatore** [comment]
I very much disagree with the view that security can’t be improved through a 
pre-publish policy. Note: never was a discussion about security being 
“insured”.

Bad software is bad software, whether released open source or kept 
proprietary. If simple vulnerabilities are not removed before releasing 
either way, it is bad software. We have long history of this with open 
source software where security was not part of the pre-release criteria 
(BIND comes to mind) compared with open source software where security is a 
consideration .

Yes, always better if security is considered line by line and no “arbitrary 
bars” are needed . Open source software certainly has not proven that is the 
case any more than proprietary software has.

Bottom line is that there is the totally un-curated model and the curated 
model – the latter has many real world benefits, especially in a world where 
the same well known security vulnerabilities (easily detected) continue to 
show up in code.

John P.

**Comment by johnmod3** [comment]
@johnpescatore I very much agree with you and would hope that during the process of developing code is developed in an open manner for all to see during development, not just as a drop release of code at version 1.0 or whatever. And actually for the gov to accept code per regulation they should be using code checking tools, test coverage, etc. Some don't ask for this data. Testing of the code before release will just create a bottleneck and could stop progress

**Comment by AlvandSalehi** [comment]
Thanks to everyone who has commented on this thread.

@johnmod3 You mention “for the gov to accept code per regulation” in your last post. Do you mind pointing us toward the regulations you're referring to?

**Comment by johnmod3** [comment]
@AlvandSalehi each agency sets its own process for approving software, I'm familiar with DoD policies which defines 'acceptance testing' for military systems. Some ref's: 
http://www.navair.navy.mil/nawctsd/Resources/Library/Acqguide/test-gpi.htm
also see: https://en.wikipedia.org/wiki/MIL-STD-498
- in general though, there are too many rules that no one knows about
