### ISSUE TITLE
Open source  is a process, not a product == Developed under public peer review (i.e. on a public Github)

### ISSUE THREAD

**Issue by rafael5** [WhiteHouse/source-code-policy#45]
This is a follow-on issue to issue #12.  (what percentage of government funded code should be released to the public).  The consensus on the issue of what percent of government-funded software needs to be released as open-source is 100%.    

However, focusing on percent of code published to the public as result of a government-funded development project somewhat misses the point of open source.

The real benefit of open source is the process and community that it builds, and the quality of code that results.

Open source "the process"  allows other coders to provide feedback  contemporaneously as the code is being developed.  This makes for better quality code.   It also creates a large community around it.  Which also builds confidence in the end users of the software that they will have support for the software if they adopt it. 

But this requires contemporaneous peer review of the code in flight.

Therefore, a better framing of any policy regarding open source should state  "100% of government-developed code should be _developed openly,  under public, contemporaneous  peer review_  by default"

As an example of this, see the DoD's contracting language. It mandates the use of a Project Repository on a _public Github repository_  for contemporaneous public, peer review .

https://github.com/vistadataproject/documents/blob/master/Submissions/src/VistAMetadata-2015-12-09-PWS.md#data-rights

1.6.15.1 Artifact Repository: To facilitate the management, reporting, collaboration, and continuity of access of all artifacts and deliverables produced under this contract as a single logical unit, all artifacts and deliverables shall be developed, version-controlled, stored, and delivered on an industry-standard public Github repository (“Project Repository”). Upon commencement of the contract period, the contractor shall establish the Project Repository, and provide the URL of the Project Repository to the project manager, contracting representative, and relevant stakeholders.

**Comment by ghost** [comment]
Peer review and online collaboration are some advantages, but not the only ones and sometimes they are in fact not applicable (if a program doesn't have a big community around it.) There would still be significant economic advantages (from the public's point of view) to open sourcing code even if it was initially developed in secret, and even if there wasn't a large enough community around it to have the specific advantage that you talk about. The more subtle advantages would still exist.

However, you still bring up a good point and I believe it would be useful to develop things openly from the get go - it may be particularly useful if in partnership with other countries' governments. That being said, I definitely do not want the government to endorse a company like Github, just for the sake of fairness and neutrality in the market. It would also give the hosting company some undue political influence. So I think the only feasible approaches would be a p2p or self-hosted system, although those might require much more maintenance depending on how they do it.

**Comment by Conan-Kudo** [comment]
It would make a lot more sense for the government to host its own service and provide a means for people to do it there. A customized and branded version of [Pagure](https://pagure.io/pagure) or [GitLab](https://about.gitlab.com/) hosted on their own systems would provide the necessary assurance that they weren't endorsing the usage of a proprietary product while developing FOSS.

**Comment by rafael5** [comment]
I agree. This surfaces an important point:  The government should not
endorse any particular vendor of any technology.

And hosting their own code repository / distributed VCS is precisely what
government agencies currently to.  The reference to Github was because many
government agencies have adopted it as their de-facto code development
repository.

One won't find too many businesses with mission critical functions
depending on bulletin boards  for tech support.  They will want a 24/7
support line, and will be willing to pay for it.  Thus the emergence of the
 "commercially supported open-source industry". Red Hat Linux is the prime
example.  In the git repository space,  Github and GitLab appear to be good
examples.

The key thing about software is the community.  If nine million programmers
around the world are developing their code on Github, why shouldn't
government and its government contractors join the party? This allows
government to be technologically compatible with their private sector
developers.

Again, since the point of using an open-source technology is to put it into
the hands of the most number of developers  (i.e. no cost, no licensing
encumbrances),  and thus foster a vibrant community around the software,
the choice of technologies is critical.   However, this cannot be a
top-down decision; it needs to evolve from the bottom up.

Rafael

_Rafael Richards MD MS_
_202-469-1527_

**Comment by Conan-Kudo** [comment]
@rafael5 If that's the case, then commercially supported open source source code repository management software brings it down to GitLab, who offers professional support in the form of their "Enterprise Edition" and [can be paid to create open source customizations](https://about.gitlab.com/development/) to allow for automatic bidirectional mirroring (they already have unidirectional mirroring now) and other necessary features, so that developers and other people can access the resources on their preferred platform, such as GitLab.com, GitHub.com, and others, while freely allowing contributions to flow from anywhere.

@dosire from GitLab would probably be able to give more color on this, though.

**Comment by dosire** [comment]
@rafael5 we would be very happy to help you set up a server to host the source code completely based on the open source GitLab CE. Joost from our team will reach out to you.

**Comment by skybristol** [comment]
Very interesting thread and points on open source as a process (and mentality?) more than a license or product.

One point here is that there's another OMB memo ([M-10-23](https://www.whitehouse.gov/sites/default/files/omb/assets/memoranda_2010/m10-23.pdf)) that essentially states that if a government agency is going to use a third party distribution mechanism for government information then they also need to provide a .gov alternative. Part of the thinking is on providing a way for people to get that information from a trusted source. So, that does mean that if government runs an open source project on GitHub or elsewhere, it also need to provide some alternative back on their own servers to get access to the material.

While I get the dynamic of not wanting government to endorse some particular commercial, non-profit, or any other private entity, I disagree with @Conan-Kudo and @rafael5 on the notion of having government do all its open source business in its own crystal palace. GitHub is kind of the go to place where much of this activity is popping right now; it used to be SourceForge, and it will be something else in another year or so (especially with the blossoming of real time collaborative code development platforms). If we really want to open government software development to live, real time peer review, then we're better off having that go on in the environments where people are doing that work already from other institutions. It doesn't matter what software government uses on its own systems if no one knows about the projects and no one comes to play.

On the whole issue of peer review, I absolutely agree with you, @rafael5. We're slowly starting to see interesting shifts in some sciences where the vetting of scientific ideas that is often encoded in software algorithms is being tested and sifted as those ideas are developing. The really exciting thing to me is seeing scientific experiments playing out in GitHub and other repos where negative results sometimes become part of the living and accessible record instead of only the final distilled product in journal articles. Having scientific workflows available through platforms like Jupyter means a potential acceleration in new scientific discovery when we don't have to decode and recode those workflows from prose documents. The competition for science funding is certainly fierce, and researchers in many fields worry about guarding their intellectual capital (including data and software) until they gain tenure at a university or achieve a high enough grade level in government. But I think we're seeing more and more young researchers able and willing to move fast enough that they're not worried about opening up their lines of inquiry to real time scrutiny, review, and comment. If humanity is going to survive past the next few centuries, I think we're going to need a massive acceleration in learning and discovery brought about by a revolution in how we think about sharing and communicating research.

**Comment by Conan-Kudo** [comment]
@skybristol I do not disagree with the idea that the software must be available in places where people can see and hack on it. But at the same time, part of this effort is all about encouraging more FOSS, because it is something that is a public good that engenders trust and enables a more engaged populace.

Additionally, being fully reliant on an external commercial provider that in itself is not FOSS is foolhardy at best, and downright dangerous at worst. Just yesterday, GitHub was being hammered, and in the past, it was attacked for hosting things people in some countries didn't like. And that's the potential problems where GitHub is assumed to not be a potential malicious actor. At least SourceForge was indeed open source and you could deploy [FusionForge](https://fusionforge.org/) (a descendant of the SourceForge software) on your own systems ([Debian Alioth](https://alioth.debian.org/) is the most well known FusionForge deployment).

While that's not to say that a similar attack couldn't happen to a government hosted server, simply having more than one location for its actual existence makes it considerably harder for the information to "disappear". Having two canonical sources that remain in sync in perpetuity makes it more likely that it will survive.

Today, I can find several software packages whose source code is no longer available in their original project site (either the project is gone or they've gone closed source or whatnot) simply because someone packaged it for a distro with its sources and I can go and retrieve it.

However, software that government(s) rely on is infinitely more critical than some text editor program, and having multiple official canonical sources that are kept in sync and allow the widest array of people to freely contribute makes for a better process, a better project, and in many cases, a better product.

**Comment by royfielding** [comment]
I also would have preferred that the policy focus on _open development_, rather than just open source, since my own experience is that the benefits people typically ascribe to open source only appear when a project adopts open development as its core principle. However, I think the policy does a good job of highlighting the advantages of open development in [section 5.2](https://sourcecode.cio.gov/OSS/#5-2-membership-in-the-open-source-community); I suspect it would be hard to improve on that, short of writing a book on the subject.

I describe Open Development as a virtuous cycle of open source, open standards, and open architecture, working together to ensure that a community can effectively collaborate on the product, extend the software in a variety of ways without requiring a single, central consensus, and yet retain the essential interfaces necessary to interoperate with other independently developed extensions and third party products. This style of development helps retain the communal spirit necessary to maintain an open source project over time and encourage essential feedback through the community participation.
