### ISSUE TITLE
How is 20 percent of newly-developed code quantified?

### ISSUE THREAD

**Issue by abutterworth** [WhiteHouse/source-code-policy#47]
The document contains a requirement to have 20 percent of custom code released as open source, but doesn't specify how this should be measured. Two possible methods:
- 20% of projects
- 20% of lines of code

What is the intention of this 20 percent? Thoughts?

**Comment by johnmod3** [comment]
i'd say lines of code, but this will be impossible to measure

**Comment by febrezo** [comment]
This is is an issue even if carefully defined as it could lead to easy ways of _cheating_ (can we call it cheating?) by counting comments, licenses, documentation and so on. Those things are needed in any project, but it should be clarified whether this would be considered or not so as to avoid future misunderstandings about what to expect from the implementation of this policy. 

Regarding the contents, it says:

`Each covered agency shall release at least 20 percent of its newly-developed custom code each year as OSS. Custom code is defined as code for all custom software projects, modules, and add-ons that are self-contained. When deciding which custom code projects to release, each covered agency should prioritize the release of custom code that it considers potentially useful to the broader community.`

Thus, I agree that it would be very difficult to draw the line between what is the newly developed code and what is code reused from bigger projects such as Apache Storm, Solr, etc. With which upstream version will it be compared? The initiative sounds good and is a good step in the appropriate direction but the metrics are really difficult to implement transparently and effectively. Some work to be done there.

**Comment by mikeBeviBevi** [comment]
I think the self contained part is important although this is really dependent on design.  One could easily choose to not use modular design.  So to answer the question, I think its 20% of self contained modules of code.

@johnmod3 Lines of code is actually a really easy measurement to get and we require that metric as part of deliverable in some cases.

**Comment by johnmod3** [comment]
@mikeBeviBevi easy IF you collect that info, DoD does to some extent. The regime for gathering stat's would probably be bigger and more of a pain that just releasing it wholesale

**Comment by DaniAkash** [comment]
@abutterworth lines of code can't be considered as exact 20% of the project. Hence it must be a measure of the modules that are developed in the project.

**Comment by benrayfield** [comment]
I propose that instead of "20% of code" it say "the best 20% of generally reusable code".

**Comment by stuartpb** [comment]
I think this should be scrapped and replaced with a much-easier-to-quantify **100%**. Why should _any_ of this code be kept proprietary?

**Comment by benrayfield** [comment]
Code is usually kept proprietary for at least 1 of these reasons:
(1) It calls internal secret systems (which they may be under contract to not opensource), so nobody else would be able to use those parts.
(2) It would be bad for reputation for the public to know what kind of junk code they write, before improving some of it.
(3) To hold power over others.

(1) may be an ok reason, but (2) and (3) are not. Publishing all your code is a great way to hold yourself to a higher standard, though I often release only what I think others would be able to reuse and not my quickly written disorganized experiments.

**Comment by david-a-wheeler** [comment]
If 20% is to be measured, I strongly recommend using _dollars_ as the unit of measure.

There are many ways to measure source lines of code (SLOC), so it's hard to measure and combined, and no one really cares how many SLOC were created anyway The real question is, how much of the government's investment in custom software has made it back to "we the people" who paid for its creation?  And investment is normally measured in dollars.

It's also easier information to collect.  It won't be trivial (because software development costs are often buried as part of other things), but it's _much_ easier to separate out than SLOC.

**Comment by mikeBeviBevi** [comment]
Just FYI,
SLOC is a measurement used for deliverables in the federal government.  I would suspect that the cost would vary greatly between contracts.  Often time cost for SLOC has other things tied into it as well such as documentation testing and what ever other processes are rolled into delivering the change.

Not all code is priced equally and it is not necessarily indicative of quality or functionality (although it should).  It's simply due to the agreed upon contract.

**Comment by jawz101** [comment]
It should stipulate code sufficient to consume input and produce output with samples of each input and output.

**Comment by royfielding** [comment]
I suggest that it should be 20% of custom development projects initiated. The point of the 20% figure is for establishing the policy as a pilot program, so that it can be introduced incrementally rather than all at once. Focusing on lines of code or size of project would be beside the point.
