### ISSUE TITLE
Scientific Software

### ISSUE THREAD

**Issue by skybristol** [WhiteHouse/source-code-policy#55]
I do not see a discussion in the draft policy on scientific software such as analytical codes and workflows built in something like Python, R, or other software platforms popular in the sciences, with many open science code projects operatingright here within GitHub. In many cases, the open release of this type of software is being pushed by publishers and journal editors who are beginning to demand the availability of software underlying scientific papers. However, that direction with commercial publishers can also introduce its own challenges to openness with some groups beginning to offer services for hosting scientific codes behind the same paywall as their journal articles. While I don't begrudge the commercial publishers' right to build commercial success, scientific code and scientific data are the fundamental building blocks whose open access is critical in accelerating the pace of scientific discovery to face our planet's pressing challenges. It would be helpful for this policy to make mention of scientific software to help bolster the overall administration push on open science ([2013 Holdren memo](https://www.whitehouse.gov/sites/default/files/microsites/ostp/ostp_public_access_memo_2013.pdf)).

**Comment by chipmonkey** [comment]
It seems to me that scientific software would be an impacted subset of all software covered under the policy; I agree that it's important, but may I ask what makes it worth calling out _specifically_?

I'd probably support a simple change that referenced the Holdren memo to which you linked, and added a small mention, if you wanted to build a pull request, but I'm not sure I see it as essential since scientific software would be covered like any other.

My main concer is just: can we think of other specific areas of software development that we should or should not single out?  Client/server, mobile, HIE, data, whatever... each are their own little niche.  I get your point, I just don't want to muddy the waters.

**Comment by skybristol** [comment]
Good point on not getting into specific kinds of software. We actually took the same tact in a recent agency level software release policy I was involved in, and I should have thought of that here. I'll look for a reasonable place to slip in a point about the open science memo as I do think that is relevant in this context.

Thanks for the response.

**Comment by treysp** [comment]
**Previous comments**
As mentioned in the previous comments, it's clear from the document's definitions of "software" and "source code" that scientific code produced by government employees is covered under the policy. Also, there are legitimate concerns about not muddying the waters by referencing specific subsets of software. However, scientific software and software production have some unique characteristics that may require additional guidance for code-release policy.

**Types of scientific software**
First, I think it's useful to differentiate two types of scientific software: that created to be reused (e.g., linear algebra libraries like [LAPACK](http://www.netlib.org/lapack/) and R packages hosted on [CRAN](https://cran.r-project.org/)) and that created to produce results used in a specific scientific manuscript or other data analysis product. The former fits comfortably under the general/colloquial umbrella of "software" in that other softwares, including COTS, likely exist as alternatives. In contrast, the latter has no alternatives by definition since no one has ever written the specific manuscript a given scientist is writing so has never conducted the specific analysis a scientist is conducting (even if she is analyzing the same data for the same generic purpose).

Therefore, code written for specific scientific analyses has distinct characteristics that must be addressed in order for government agencies producing it to have uniformly understood guidance on how to release such code to the public.

**Linkage between code, manuscripts/products, and data**
1 - Code for specific scientific analyses is meaningless unless it can reliably be linked to the product(s) resulting from the analyses. For example, the code used to produce the analysis for Manuscript X being publicly available is useless unless the public can identify the linkage between the code and Manuscript X. 

Requiring that documentation for such code list (and ideally link to) the data product(s) that used it would prevent useless orphaned code being pushed out just to meet code release requirements. Explicitly differentiating code/software created for specific scientific analyses from other types would allow such a requirement to be narrowly tailored.

2 - Code for specific scientific analyses is useful without the data that were analyzed because the findings in the published data products become more transparent, but they are much more useful if the code can actually be applied to the data. 

This is where the relationship to the Holdren memo becomes clear, but it also demonstrates the utility of an additional piece of documentation - clear description of what data were analyzed by the code, ideally using appropriate metadata schema and including actual links to the hosted data on government platforms.

These documentation requirements for scientific analysis code - listing of data products the code generated, listing of data analyzed by the code, and links to the location of the hosted data - increase the utility of open-source scientific analysis code by an order of magnitude or more.

This level of additional documentation may be enough of a burden that scientific agencies balk, but the value of scientific analysis code floating out there alone is essentially nil without these pieces of information. I'm not sure if this policy is the place for guidance specific to scientific analyses, but these documentation requirements will be critical to producing actual value to the public from public scientific code.

**Nature of scientific collaboration**
Unlike development of much software, scientific analysis code is often produced via collaboration between federal employees and non-federal employees without any formal contracting mechanism. The government clearly benefits from such work, and non-federal employees are willing to collaborate because the analyses produce the scientific manuscripts academic scientists are rewarded for. (There are also formal collaborations with companies, particularly those that produce valuable IP like new drugs, but they are mostly covered by the policy as written.)

These non-contractual collaborations are extremely valuable for government science, as government scientists gain access to expertise and methods/equipment not available to them. The benefits are particularly large for analyses of sensitive data that cannot be released to non-federal scientists.

However, incentives for scientists to make their data and code public are still uneven and shifting. If the policy treats scientific code developed collaboratively as written by federal employees and subject to mandatory release, government access to highly skilled scientists may decrease. This is a significant concern that is relatively unique to scientific software - careful consideration of this is necessary and detailed guidance in this or another policy would be very valuable. Perhaps a time-delayed required release or specific licensing approach would address this issue?

**Comment by roomthily** [comment]
A better clarification would be between research software produced by federal employees/contractors and research software produced by researchers through a federally-funded grant. The first should fall under the (F)OSS policy for software generally; the second has been an open question on the PI side for all of my 15 years of grant-funded experience - is it public domain? Is it licensed? What license can you use? Does it differ by agency? Are you collaborating with a federally-employed researcher? And would that change the policy in these cases? Are there patent concerns and how is that potentially affected by the IP stance at universities?

I would note, as well, that science software has somewhat narrow connotations across domains and the provenance requirements for referencing versions or other software artifacts can't necessarily be defined by those things we categorize as "science" code or "glue" code. It becomes a question of publication and, frankly, credit (if we're talking retaining any type of research developers). Ideally, code produced for (or used by, with known limitations related to commercial code) research publications becomes part of the scientific record and should be managed and/or preserved with that understanding. (Apologies if misreading but) software access should not be predicated on data access; that neglects so much of the potential value of open research code beyond simple replication. 

If nothing else, keeping all forms of research code under the open policy allows us to move beyond these dated ideas of science code and everything else. The infusion/reuse potential of 'everything else' is a financial consideration - if it is not considered for OSS release, we are forced to reinvent wheels, limiting new research activities and software solutions and hampering the learning opportunities from these federally-funded activities. Not a fan.

**Comment by treysp** [comment]
@roomthily Absolutely agree that software access should not be predicated on data access and that all forms of research code should be under the open policy. 

As you note in #128, however, research code has potentially unique documentation issues, especially code connected to a publicly released analysis.
