### ISSUE TITLE
National security concerns

### ISSUE THREAD

**Issue by ghost** [WhiteHouse/source-code-policy#56]
I am concerned that developing open source software may result in overly/unnecessarily secure code that uses strong encryption protocols. This will likely become a significant safety issue, hindering law enforcement and investigation, as we have seen with Apple's designs. I believe a key escrow system would be the most effective solution. Information will be protected with encryption but still be accessible by authorities in case of national security or other law enforcement needs.

**Comment by eveninglily** [comment]
I disagree with your concern. Software should be more secure, especially software made and used by the government. 

Any sort of key escrow or backdoor leads is a huge security concern, and while it might aid law enforcement, I believe security and privacy outweighs that, and no such policy you suggested should be enacted.

**Comment by ghost** [comment]
Sorry, my bad for not expanding this idea. I also forgot to mention the most important component. We would provision access to key escrow using very strong, unbreakable encryption. Then the appropriate leaders and lawful authorities receive access to the keys through a super secure database or file system that can verify access privileges. I don't think of it as designing _insecure software_, but designing **safe software**. The keys are kept from hackers and bad guys by using the _best encryption possible_.

Done properly, we can have the best of both worlds, combining safety and security. All government software would transmit and store data with strong encryption, but law enforcement could access critical information when needed, because they alone have the keys, and these keys are protected with very secure protocols. So all software is properly encrypted, especially the key escrow mechanism, but authorities would have access the the first layer of data by using their special key, which is also encrypted. Essentially, it's a double lock, and that seems to actually be more secure, as we'd be using two encrypted levels.

**Comment by benjamin-allen** [comment]
Understand that the implementation of such things goes against the basic ideas of security. Expecting me to trust the government with security tools it didn't create and isn't intimately familiar with is akin to expecting me to trust a child with the launch systems to our nuclear weapons. They might understand that it's really important, but the actual severity of a single misstep can elude them entirely. 

In addition, assuming that the keys would be protected from an outside attack (unlikely: need we forget that the records of millions of federal employees were compromised from an outside attack), there's no guarantee that they would be safe from an inside attack. All it would take would be a single corrupt person to bring the whole system down. Furthermore, those keys now become a very lucrative target, and the hackers of the world are smarter than people give them credit for. Inviting attacks by inventing the master key will not end well.

Finally, we've invented encryption for a reason - namely, that people dislike being spied on by anyone, benign or otherwise. It wouldn't be difficult to imagine that, if this master key were invented, people would switch to a different method of encryption whether it was legal to do so or not.

To close: "People willing to trade their freedom for temporary security deserve neither and will lose both.” ~Benjamin Franklin

**Comment by ghost** [comment]
I see your points now very clearly. These are wise thoughts; thank you. People would become targeted for their access. That is troubling and really pokes holes in this idea. We shouldn't do this. It would be too dangerous to create a key escrow system.
