### ISSUE TITLE
All government-funded code should be public domain

### ISSUE THREAD

**Issue by luke-jr** [WhiteHouse/source-code-policy#58]
The money comes from the taxpayers. I don't see any legitimate reason to hide the code or claim copyright to it...

**Comment by camerons** [comment]
I'd be wary of entertaining the possibility of "Securing Federal Government-wide reuse rights" as an alternative to "Open Source Software". Merely securing "government reuse" fails to gain one of the key advantages of Open Source, namely that if I give away my software for free, then external governments and organisations are more likely to adopt the software, support maintenance of the software, extend the software, which in turn is of direct benefit to the US Government.

**Comment by luke-jr** [comment]
I certainly didn't mean the former. As the public funds the software's development, the software code should be public domain and freely available to any citizen to do what they like. (If the government also wants to open it to outside contributions, all the better...)

**Comment by destenson** [comment]
I work for a contractor who sometimes writes code for use by and funded by the government. There are several legitimate reasons why that code should not be made publicly available. Although, I agree with the premise of your statement in general, it cannot be responsibly applied as a blanket statement to all publicly-funded source code.

**Comment by luke-jr** [comment]
If contractors don't like the terms, they can always choose not to work for the government.

**Comment by destenson** [comment]
Do you want all people in the world having access to the source code that makes ballistic missile systems, satellite communication, radar systems, surveillance systems, nuclear reactors, etc. work? Should we make all hardware open source as well? C'mon, be realistic. It's a nice goal to have everything be put into the public domain, but there are practical restrictions to that. The major purpose of the government is to protect the common good of its citizens. Making some projects so open would be detrimental to that purpose just to fit into a philosophy.

**Comment by luke-jr** [comment]
Not only is the evidence strongly in favour of open source being more secure, there is no evidence closed source has _any_ real security benefits at all. What harm can someone do with the source code for any of the above-mentioned systems? (None.)

**Comment by destenson** [comment]
Are you kidding me? With the source code to any secure system, you have the capability to find and exploit vulnerabilities in the system that the user of the system may not know exists. The harm that can be done with this is immeasurable.

Open source is _not_ more secure just because it's open. It **becomes** more secure over time as flaws are discovered (sometimes before exploitation and sometimes after) and fixed.

**Comment by destenson** [comment]
Sure, in theory, all software is perfect, all source code is flawless & all best practices are used and there are no flaws anywhere in the system. In that case, there's no problem with all source code being all public. But that is not reality. Real life gets in the way of your philosophy.

**Comment by destenson** [comment]
Open source software converges on secure over time. It's definitely not intrinsically secure just because the source is available. There are several use cases (such as those I mentioned) where it's not acceptable to risk waiting for that convergence just because you feel like the code should be open.

**Comment by luke-jr** [comment]
Yes, that's beside the point. If the system is so critical that any temporary insecurity cannot be tolerated (missiles), the only solution is to keep it off hostile networks entirely - I sure hope that is already the case. Hiding the code provides no benefits in this.

**Comment by destenson** [comment]
If the realities of existence here on Earth are beside the point, what is your point?

You're so short-sighted. Security isn't limited to networks. The bottom line is, with access to the source code, you have the capability to exploit vulnerabilities in the system. Some of those vulnerabilities are intentional to assist in development and debugging, and others are unintentional & unknown. Ideally there would be no vulnerabilities, but this is real life & when you write code, you write bugs, it's inevitable. Maybe you should stick to talking about things you know something about.

Answer me this, how many security flaws have been revealed in the history of OpenSSH? It's open source, therefore it's intrinsically secure, and so there have been no flaws, no vulnerabilities, right? Yes, being open source has allowed those vulnerabilities to be found more easily since potentially millions of eyes can scrutinize it. Open source is a "good thing" in general. There are cases where it's not. Is it a "good thing" when enemies of your citizenry are allowed to audit your code for vulnerabilities? This isn't just private keys on a web server, or a few bitcoins in your software "wallet", or credit card numbers, or identity theft, this is life & death.

**Comment by luke-jr** [comment]
> The bottom line is, with access to the source code, you have the capability to exploit vulnerabilities in the system.

This is equally true without access to the source code.

> Some of those vulnerabilities are intentional to assist in development and debugging,

Sounds like we should fire those incompetent developers.

Just going to ignore the straw-man.

**Comment by destenson** [comment]
> This is equally true without access to the source code.

Saying something is true doesn't make it true. Are you saying that it would be equally as easy to exploit the vulnerability of a software system when all you have is inputs & outputs, as when you have the source code that specifies what the system does with those inputs to convert them into outputs? I don't even know what to say.

You seem to be the expert at straw man arguments as you haven't been able to rebut a single one of my actual arguments. All you have to say is that open source is secure & closed source is not. Reality begs to differ.

> Sounds like we should fire those incompetent developers.

So you've never written a back door into a complex system in order to assist in debugging? You've never used a remote debugger? You've never used a debugger, period? All those things present intentional vulnerabilities into the system. No one writes non-toy, non-academic code without using these tools.

(And if we're going to start firing all the incompetent people in government, there will hardly be anyone left. Again, reality strikes. There are incompetent people working for us. That's a fact and we have to work within the constraints that reality provides.)

I'm not going to continue arguing with you. You've made your point & I've made mine. I'm just glad the people who are responsible for deciding this know that your philosophy isn't practical.

**Comment by luke-jr** [comment]
You'd have to make an actual argument to rebut. Instead, you've merely made ad hominem attacks and gone after straw-man claims you made up.

**Comment by camerons** [comment]
luke-jr, destenson, maybe it is time to agree to disagree. There are plenty of online debates addressing similar points you both raise. I suggest our key message as reviewers should be that this Source Code Policy should aim to resolve this debate, such that it need not distract implementers of this policy.

**Comment by destenson** [comment]
The original poster asserted that "All government-funded code should be public domain" since "the money comes from the taxpayers. I don't see any legitimate reason to hide the code or claim copyright to it..."

I entered this discussion as, not an opinionated bystander to stir debate, but as someone with specific domain knowledge on the subject (that I cannot share specific details of, for what should be obvious reasons). Just because he doesn't "see any legitimate reason" to keep code secret, doesn't mean there aren't any. I simply wanted to express what I've already said, I agree that publicly funded source code should generally remain free and in the public domain, but there are practical and necessary exceptions for which it's the government's obligation to keep secret in order to fulfill its duty to protect the rights and lives of all citizens.

EDIT: I apologize for taking over this discussion like this. I came in from outside and I saw the blanket statement directed at source code policy of the White House and I felt the need to chime in since it didn't always apply in every case. Now I realize that this was not the place to discuss this. I won't say any more except that I agree that source code originated by the government and released to the public should be in the public domain or under whatever license the law requires.

**Comment by destenson** [comment]
> You'd have to make an actual argument to rebut. Instead, you've merely made ad hominem attacks and gone after straw-man claims you made up.

You'd have to read, understand, and respond intelligently (not just a one-liner dismissing it as if I'm making things up) to anything I said make it sound like you care about the outcome of this discussion.

**Comment by destenson** [comment]
If you'd like, I'll delete all my comments, since they're not relevant to this repository's issue.

**Comment by luke-jr** [comment]
I wonder if it would satisfy @destenson 's concerns to simply allow for classification of certain software as confidential the same way other information currently is (which is definitely outside my area of knowledge).

**Comment by destenson** [comment]
I don't know the legal implications of that classification (as it's definitely outside of my area of knowledge as well), but on the surface it sounds appropriate. There are definitely legitimate reasons why some information including source code should remain confidential. Thanks.

**Comment by luke-jr** [comment]
Why was this closed?

**Comment by konklone** [comment]
@luke-jr See #249.
