### ISSUE TITLE
Strengthen language on public domain status outside the USA

### ISSUE THREAD

**Issue by b-k** [WhiteHouse/source-code-policy#68]
The head of Section 4 points out that the US copyright code does not apply to software originated by gov't employees.

But this leaves open the option of putting restrictive copyrights outside the USA, which zealous agency lawyers may do (and yes, I have seen this happen). Such a dual license clouds the waters to no serious benefit. Can a non-US contractor improve the codebase? Does a US company with servers in Canada need a dispensation from the US gov't? Would the US gov't ever seriously contemplate selling the code to a non-US buyer?

I thus recommend adding verbiage explicitly recommending and permitting authors to list their code as CC0 at the head of Section 4.

**Comment by murpup** [comment]
> Would the US gov't ever seriously contemplate selling the code to a non-US buyer?

The answer to that is yes.  My agency has created cooperative research programs with other countries whereby regulatory agencies and commercial companies in those countries pay us a yearly fee along with 1-2 in-kind contributions per year (usually in the form of code validations, experimental data, or code changes) and in return they are given access to and permission to use our scientific simulation codes, as well as periodic training every few years.  See http://www.nrc.gov/about-nrc/ip/research-programs.html
We benefit because the burden to the taxpayer is lessened and our codes get exercised and validations performed by a larger user community than they otherwise would.  The other countries benefit because they do not have to place major development resources of their own into developing their own simulation codes which can cost anywhere between 20 to 100 million dollars over a 10-20 year period for some of the more complex codes.
