### ISSUE TITLE
What about datasets, in addition to software

### ISSUE THREAD

**Issue by jameslaneconkling** [WhiteHouse/source-code-policy#71]
This policy only addresses federally-funded software projects, but does not mention datasets generated by federally-funded projects.  I know there is as much or more talk about opening up datasets--curious to know if there any complementary policies mandating the open licensing of datasets.

**Comment by mhogeweg** [comment]
hi, you'll be interested in [Memorandum M-13-13](https://www.whitehouse.gov/sites/default/files/omb/memoranda/2013/m-13-13.pdf) and the implementation guide over on the [project open data site](https://project-open-data.cio.gov/implementation-guide/).

**Comment by jameslaneconkling** [comment]
@mhogeweg thanks for the links.  

Seems that M-13-13 is more of a best practices guide, given that there are not hard requirements for open licensing of datasets, if the agency in question chooses to categorize a dataset as _enterprise data_.  No doubt a good foundation, though w/o requirements for obligating openness.

**Comment by jlberryhill** [comment]
Thanks for the input, @jameslaneconkling and @mhogeweg. M-13-13 is formal policy and obliges agencies to assume a "by default" stance in opening data to the public. The goal of the Enterprise Data Inventory (EDI) is to catalog all data in the respective agency (i.e., enterprise), not only all data that @mhogeweg refers to as "enterprise data." You may also be interested in M-13-13's companion website [Project Open Data](https://project-open-data.cio.gov/), which provides best practices, tools, and resources for agencies. The draft Source Code Policy proposes a similar site called Project Open Source geared toward source code instead of data. 

cc @justgrimes

**Comment by jameslaneconkling** [comment]
@jlberryhill thanks for the link.  By asking about obligations, I was wondering what the requirements were to justify keeping government-funded datasets behind a paywall, which are outlined in section **D: Document if Data Cannot be Released**.  Thanks for sharing.

**Comment by jameslaneconkling** [comment]
@jlberryhill is there anywhere in M-13-13 or elsewhere that documents the requirements dataset paywalls?  Much of the discussion around the difference between public, restricted, and private data licensing has to do w/ issues of personal privacy and security, which would not apply to licensed datasets.

**Comment by jlberryhill** [comment]
@jameslaneconkling -- Mind opening an issue on the Project Open Data issue [tracker](https://github.com/project-open-data/project-open-data.github.io/issues)? There's an active open data community there that could also engage.

**Comment by jameslaneconkling** [comment]
cross posted.... https://github.com/project-open-data/project-open-data.github.io/issues/553

**Comment by jlberryhill** [comment]
Thanks! I asked a member of the team to look into.
