### ISSUE TITLE
Email Comment: Public Comments

### ISSUE THREAD

**Issue by OMBPublicComments** [WhiteHouse/source-code-policy#77]
[Email Comment: Received Thu 3/24/2016 5:23 PM EDT]

To whom it may concern,

Please find below comments on federal source code policy. Also questions are embedded, but I obviously do not expect a reply. They are questions I hope for which you will seek answers.

• Who is creating a list of potential unintended consequences? I hope there is a group within your office who can do this. I am trying to call a few out here.
• Who is going to pay for the extra work involved in documenting, uploading, etc. the custom software so that it becomes available as OSS? The government should calculate how much more costs are incurred to go to the OSS model regardless of how much the government believes can be saved. The cost increase calculations should be shown to the public. We can do math, so we would like to see Net Cost Change = Net Savings – Net Additional Costs. And, possibly use high-medium-and low scenarios for each to get a potential range of cost change. The uncertainties in savings are enormous, but the uncertainties in cost increases to go the OSS model are more quantifiable.
o   For example paragraph 5.2 requires: “covered agencies should develop and release code in a manner that (1) fosters communities around shared challenges; (2) optimizes the ability of the community to provide feedback on, and make contributions to, the code; and (3) encourages Federal employees and contractors to contribute back to the broader OSS community by making contributions to existing open source projects.” Items 1-3 require extra work – work that would not otherwise have been paid for if there was no OSS initiative. What are the extra costs (could be an extra 5% of the base effort, for example)?
• How is the government going to ensure the viability, robustness, stability, etc. of the uploaded OSS software? Will there be extra steps the contractor must take prior to uploading the code (e.g., documentation)? Having a huge repository of code whose pedigree is unknown is not very useful and could in fact add more costs than savings over the years.
• A contractor’s priority will be delivering functioning code to their customer and not necessarily making it easy for someone else to use their code. What negative ramifications may result?
• At what level will custom code be uploaded by contractors? Answers can range from entire enterprise applications with 100s of thousands of SLOC to individual functions and DLLs that perform very limited tasks. Will each be documented in the same way. For example, will each function within the enterprise application require as extensive documentation as a single/limited function would require?
• How will the gov’t prevent “the public” from introducing back doors directly into source code? This seems like a serious risk that should be addressed.
• Covered agencies include: “the term “agency” means any executive department, military department, Government corporation, Government controlled corporation, or other establishment in the executive branch of the Government.” Really, the Department of Defense will be a covered agency. In the midst of all government and military organizations and military contractors being attacked every day by nation-states and terrorists, we are going to open-source all of the software the defends the nation? Okay, I see later the National Security exemption – that’s good.
• Per the draft (3.Step 1), government employees will be required to conduct an AoA before procuring software. Do government employees have the expertise to do this? Will additional government employees have to be hired/trained to perform this function? 
• What type of consistency does the government expect from OSS? For example when evaluating various gov’t OSS solutions, does the government expect to be able to fully execute all features of existing systems? Thus, many different cases/scenarios of input would also need to be within the repositories. Will people looking to re-use software really have the info they need to efficiently evaluate it?
• With the continued rapid evolution of operating systems and obsolescence of current software, it would seem that large portions of the government OSS repository will go “stale.” 
• Per the draft paragraph 5.1, the 20% figure is arbitrary. Each agency should be able to determine their own goal based on their current operations. 
• Para 5.2b is overreach. This rule is dictates how agencies and their contractors do development. For example, requiring code to be released to the public for bug fixes is quite ridiculous and comes with a host of problems.
• Para 5.2d – new work. What is the additional cost?
• Para 5.2f – new work. What is the additional cost?
• Para 6.Code Repositories and Inventories – what is the additional cost?
• How is the government going to prevent duplication of effort? Being a contractor for my entire career, it is well known to me and government employees how various government agencies, departments, etc. compete with one another. Even branches within the same agency compete and often duplicate (or very nearly duplicate) work. Under OSS, a capability that at one time was developed and “owned” by one government agency (i.e., the taxpayers pay for it once), is now “free” to be pulled into and developed by a competing government organization. The new organization will of course defend its need to create a new, custom branch of the OSS software. At that point, there will be two government organizations building nearly the same capability, and this scenario is enabled by OSS. Has the government considered these scenarios?
• What economic analysis has been done on how and why software is open-sourced in the commercial community and how it may be different in the government realm? Ultimately someone, somewhere has to make revenue/profit based on their activity. I.E., a cadre of people will not just start “working on” government software if it is pushed out there. People do not work for free for long. Banking on millions of people doing $100 of free work on a government-only open software system is not a good idea. Have you considered the uniqueness of what the government does and how this uniqueness may inhibit (or not attract) large communities of interest. These communities of interest will be deploying other, more commercially applicable, code bases for profit. 
• Also, in a similar context to above, has the government considered the effect of timescales of open source development in the commercial world compared to federal government procurement timelines? How might this impact the success or failure of the this initiative? The commercial world can get things done quickly. The Federal government can take a year to get an RFP out and another year to get it awarded. 
• Open source software is considered a cyber security risk in general. Will the use of OSS change security risk or the cost of security accreditation for software to be installed on government networks?

Thank you for considering these issues and questions.
- Allen R. York

**Comment by RobertLRead** [comment]
Dear Mr. York,

I do not presently work for the Federal Government, but I thought your thoughtful questions warranted a precise issue-by-issue response. Since your comment was submitted by email, I do not know if your will see this response.

Your second question is substantive one, in which you raise the fact, with which I agree, that releasing code as OSS and documenting requires extra work, which will entail extract cost. However, I believe the extra cost will returned with a huge return on investment in the cost of maintenance. The current policy does generally seem to imply that software is a one time cost, but we all know software in the Federal government can live a long time and in fact the maintenance costs can exceed the development costs. I believe OSS software is cheaper to maintain for two reasons:
1) Those firms bidding on future maintenance contracts do so with full knowledge of the code and its quality, decreasing their uncertainty, and therefore their bids.
2) All of the time spent documenting the code and, frankly, making it less embarrassing because it will be released, will assist the future maintainers, whether they are the same firm or not.

Your third point (_"How is the government going to ensure the viability, robustness, stability, etc. of the uploaded OSS software?"_) is also extremely valid. The release of OSS is not a one-time event, but rather a process.  We should suggest wording changes in the policy that make this clear.  I believe the spirit of the policy should not be "released as OSS" but "developed transparently as OSS and continuously released in a timely manner." There will not be "extra steps taken prior to uploading" as you write, because the code will simply be uploaded the day it is written.  The pedigree will those not become unknown.

Your fourth point: "_A contractor’s priority will be delivering functioning code to their customer and not necessarily making it easy for someone else to use their code. What negative ramifications may result?_" Is undoubtedly true but I submit that only positive ramifications can accrue from contractors knowing that their code will be a matter of public record. It is true that this may increase the effort put into the code---but it is hard for me to see that that, on balance, even increases costs when all benefits of higher code quality are considered.

Your 6th question: "_How will the gov’t prevent “the public” from introducing back doors directly into source code? This seems like a serious risk that should be addressed._" is quite relevant.  The wording from line 289, section 5.2 e, is: "These kind of contributions should be anticipated, and, where appropriate, considered for integration into custom Developed Government Software" is a big vague.  I will make a pull request suggesting: "These kind of contributions should be anticipated, and, where appropriate, considered for integration **after careful code review** into custom Developed Government Software or associate materials." I do believe code review is essential to preventing bad actors from sabotaging code efforts. However, on balance OSS improves security rather than decreasing it, because if a bad actor at a firm places a security risk in the code, it may never be discovered.

Your question: "_Will people looking to re-use software really have the info they need to efficiently evaluate it?_" can only be answered: probably not in most cases. It is hard to reuse the long tail of lightly used OSS projects now. However, any opportunity for reuse is better than not even having the possibility of discovering it; we should not let the perfect be the enemy of the good.

You state: "With the continued rapid evolution of operating systems and obsolescence of current software, it would seem that large portions of the government OSS repository will go “stale.”". Yes, OSS must be a process, not a one-time release. When software is not evolving it is becoming a legacy system and a problem. However, even if the code is being under-invested, it is valuable to have it be OSS, so long as the OSS accurately reflects the true code, which is what happens when you develop in the light, rather than making a one-time publication.

You state:  "Per the draft paragraph 5.1, the 20% figure is arbitrary." I completely agree and strongly favor the "open by default" policy.

You mention some additional costs that you believe to be associated with 5.2b, 5.2d, and 5.2f. However, there are certainly benefits provided here as well. Everyone commenting on this policy, including yourself, is an example of someone making a valuable contribution without remuneration to the Federal government.

You ask "_How is the government going to prevent duplication of effort?_" This OSS policy has no hope of preventing duplication of effort, but every hope of decreasing it. It seems to me that it need only decrease duplication of effort by 12% to save the taxpayer $1 Billion per year. Surely closed software which cannot be viewed between agencies absolutely maximizes duplication of effort, right?

You ask for an economic analysis of open-source software. I do not need an analysis of altruism to know that it exists. I do not need to know why people contribute to the Wikipedia to know that they do.  If people don't contribute to Federal software efforts for free, then nothing has been lost. The "community of interest" includes the person who wants to see the code to reuse it for personal profit or to make sure the government is not spying on them or to prepare a civil rights lawsuit, even if none of those people intend to contribute code. In the modern age, code is an extension of government policy, and to keep it secret is the same as deciding a case in a court of law without a written recored of the evidence and testimony.

Finally, as the NIST and the DoD have pointed out, OSS is NOT considered a cybersecurity risk in general as you assert. There is a general consensus that "security by obscurity" is a bad practice.
