### ISSUE TITLE
Ensure procured code can be modified and reused

### ISSUE THREAD

**Issue by brittag** [WhiteHouse/source-code-policy#93]
_(I’m Britta Gustafson, a content designer at [18F](https://18f.gsa.gov/), an office in the [U.S. General Services Administration](http://www.gsa.gov/) that provides in-house digital services consulting for the federal government. I’m commenting on behalf of 18F; we’re an [open source team](https://18f.gsa.gov/2014/07/29/18f-an-open-source-team/) and happy to share our thoughts and experiences. This comment represents only the views of 18F, not necessarily those of the GSA or its Chief Information Officer.)_

The draft policy section about [Government-Wide Code Reuse](https://sourcecode.cio.gov/Reuse/) has a helpful set of two requirements for procured software to support reuse across government: delivery of code with supporting materials, and rights to all of those resources. These requirements should include a third requirement: ensuring the delivered resources can be reused as intended by the policy.

Software development and documentation is complex work. Even when experienced software contributors are working in good faith, it’s easy to forget to mention a key step in your installation instructions, and it’s even easier to forget to update your instructions after you make a change to the software. Every developer has at some point struggled with missing information when trying to set up another person’s code. As part of good software development, it’s important to check your setup materials.

Government staff with a reasonable level of relevant expertise should be able to build and deploy procured code (and modify the code and deploy the modified version) without getting stuck in difficult setup problems, especially if those problems could require additional vendor support. An example of how to help this policy work well would be to include a third item in the list of requirements:

> (3) Require validation that a party not involved in the creation of the custom source code can use the delivered items to construct a fully-working version of the software product without undue burden, and that they can then modify and run that version without undue burden.

**Comment by brimston3** [comment]
The above comment is a critically important go/no-go test for whether something complies with the intent of this policy. These are a couple things this provision helps guard against.

### Cryptographic locks preventing COTS module modification.

Scenario: 

> A third party COTS vendor creates custom module and provides source code as is required by policy. The COTS product into which the OSS-module is loaded is exempted from source release by this policy. However, the product requires all loaded modules be signed using a particular cryptographic key held by the third party vendor which they consider a trade secret. 

This configuration prevents modification and maintenance by the federal agency (and subsequent contractors) without vendor participation (vendor lock-in). It would fail the test above since the uninvolved party would not have access to the cryptographic key.

### Hardware (or bootloader) locks.

Scenario: 

> The external vendor provides all source, scripts, and documentation required to create custom firmware images to a piece of hardware which has been software customized for federal use (eg. a point-of-sale kiosk). The firmware image itself can be created, but hardware locks on the device prevent deploying the firmware image onto the hardware. For example, the installation may require special tooling (custom software or device-specific hardware) which was not provided and is not available for sale by the vendor or in the general market.

Thus the federal agency is unable to modify or maintain the software without vendor participation (vendor lock-in).

In a practical example of hardware locks, the Android operating system is open source, but for the majority of hardware platforms on which it is installed, the user cannot modify or customize their installation, even though they have source code and build tools to do so.

This would fail the test because the uninvolved party would be unable to deploy their modified code to the target device.
