### ISSUE TITLE
Ensure Accessibility to Affected Software

### ISSUE THREAD

**Issue by UndarkAido** [WhiteHouse/source-code-policy#98]
One central .gov website listing all FOSS software created by this policy would allow for easy use of said software and a greater impact on society. I believe it would be an excellent provision to add to the policy.

**Comment by mgifford** [comment]
You're talking about building code to the W3C's WCAG 2.0 & ATAG 2.0 standards?

**Comment by UndarkAido** [comment]
While that's also a good idea, I'm thinking of something like how the Play Store is where you get Android apps. A clear location for finding open-sourced government software.

**Comment by johnmod3** [comment]
@Aidoboy disagree, one repo to own/rule all the gov codes ins't a good idea. Code should reside where the developers are and fight for marketshare

**Comment by gbinal** [comment]
_[Speaking in my personal capacity]_

I believe the vision here is similar to data.gov (which harvests metadata agency.gov/data.json or govcode.org (which uses an API to query the contents of many disparate collections) - to harvest and assemble the metadata of projects that reside elsewhere.  Such a model would allow for repos to still reside wherever while still providing a comprehensive discovery tool.

**Comment by UndarkAido** [comment]
@gbinal Yes, that's what I was trying to get across. Thank you!

**Comment by UndarkAido** [comment]
Why was this closed?

**Comment by chasingamy** [comment]
@Aidoboy Per Issue #249 , The public comment period has officially closed, and we closed all of the issues submitted before the deadline in order to officially count them as part of the public record. OMB will analyze all feedback submitted during the public comment period and revise the policy as necessary. Further discussion can continue in new threads if you'd like, but they will not count as part of the official record.

**Comment by UndarkAido** [comment]
@parisj OK, that makes sense.
